### ISSUE TITLE
Guard state file correctness with a checksum

### ISSUE THREAD

**Issue by mfournier** [prometheus/pushgateway#101]
I'm not sure how I ended up in this situation, so I'll describe what I observed:

First kernel OOM-killer activity on a machine dedicated to prometheus, pushgatway and a couple other exporters. It appears that pushgateway is using several hundreds MB of memory (similar setup on another host, with roughly the same amount of events pushed to it: around 10MB).

Then taking a look at the `/metrics` endpoint, almost 900'000 lines returned, as opposed to around 500 on a "healthy" instance. Among them, a huge number of duplicates:
```
$ curl -s 0:9091/metrics | egrep '^conplicity_backupExitCode{instance="geoacorda-int-application-0",job="conplicity",volume="logging_agent"} 0$' | wc -l
2000
```

Next observation: the statefile is around 80MB in size instead of the usual 50kB-60kB. Peeking at the end of this corrupt statefile, I doesn't look the same as a healthy one, so I wonder if it might have been truncated by a transient diskfull or something:
```
$ cat -v pushgateway.state | tail
conplicity^@^A^Fvolume^A^Mlogging_agent^@^A^@^@^A^C^A^Hinstance^A^[geoacorda-int-application-1^@^A^Cjob^A
conplicity^@^A^Fvolume^A^Mlogging_agent^@^A^@^@^A^C^A^Hinstance^A^[geoacorda-int-application-1^@^A^Cjob^A
conplicity^@^A^Fvolume^A^Mlogging_agent^@^A^@^@^A^C^A^Hinstance^A^[geoacorda-int-application-1^@^A^Cjob^A
conplicity^@^A^Fvolume^A^Mlogging_agent^@^A^@^@^A^C^A^Hinstance^A^[geoacorda-int-application-1^@^A^Cjob^A
conplicity^@^A^Fvolume^A^Mlogging_agent^@^A^@^@^A^C^A^Hinstance^A^[geoacorda-int-application-1^@^A^Cjob^A
conplicity^@^A^Fvolume^A^Mlogging_agent^@^A^@^@^A^C^A^Hinstance^A^[geoacorda-int-application-1^@^A^Cjob^A
conplicity^@^A^Fvolume^A^Mlogging_agent^@^A^@^@^A^C^A^Hinstance^A^[geoacorda-int-application-1^@^A^Cjob^A
conplicity^@^A^Fvolume^A^Mlogging_agent^@^A^@^@^A^C^A^Hinstance^A^[geoacorda-int-application-1^@^A^Cjob^A
conplicity^@^A^Fvolume^A^Mlogging_agent^@^A^@^@^A^C^A^Hinstance^A^[geoacorda-int-application-1^@^A^Cjob^A
conplicity^@^A^Fvolume^A^Mlogging_agent^@^A^@^@^@^@^@
```

This is version 0.3.1 from the docker image on dockerhub (but same symptom with 0.3.0 or :latest), started with: `/bin/pushgateway -persistence.file=/state/pushgateway.state`. I have the corrupt statefile available if you want to take a look at it. Reproduicing the problem is as easy as loading this statefile in the pushgateway.

Thanks !

**Comment by beorn7** [comment]
With a corrupt state file, all bets are off. We could add more sanity checks, but the only action then would still be to discard the state.

Not sure if it is worth to investigate in more detail, unless there is reason to believe this is self-inflicted by the PGW and not due to data corruption/truncation on disk.

**Comment by mfournier** [comment]
Yes, no problem with throwing away the corrupt file, once the problem is identified.

Yet, the symptoms I encountered (overloaded prometheus, kernel killing the monitoring stack) could be avoided if the pushgateway discarded the corrupt file, or simply crashed. So +1 for more sanity checks ! Having a reliable and predictable prometheus suite is what matters the most, imho.

In this case, if prometheus wasn't constantly getting overloaded by the pushgateway, it would simply be a matter of noticing a target going up and down. Yet the first symptom for me was the prometheus server itself acting weirdly, not leaving any hint about what was going on, and getting killed shortly after startup.

Another option might be to offer a way to cap the amount of metrics prometheus is allowed to fetch from an exporter (similar to `scrape_timeout`), to have a way to guard against rogue exporters?

**Comment by juliusv** [comment]
> Another option might be to offer a way to cap the amount of metrics prometheus is allowed to fetch from an exporter (similar to `scrape_timeout`), to have a way to guard against rogue exporters?

This is happening here :) https://github.com/prometheus/prometheus/pull/2288/files

**Comment by beorn7** [comment]
At the current state, this issue boils down to "put some sanity checks in place to detect corruptions of the state file". I guess the most obvious thing to do is to add a checksum. That would change the format and is thus a breaking change (or a more involved one if we want to keep backwards compatibility – this might play well with fixing #90 at the same time, which also requires a format change).
I'll rename this issue accordingly.

**Comment by beorn7** [comment]
I take the silence as a signal that this feature would be of limited use.

In general, I think the code could guard better against null values, as that's what GOB will create if something doesn't fit. Right now, there are too many code points where the PGW would just panic. On the other hand, that's also a pretty clear signal that the state file is not fine anymore. But that would be a different story...

I'll close this to put the checksum part off the agenda. Feel free to comment/re-open if you think otherwise.
