### ISSUE TITLE
Allow for multiple levels in path

### ISSUE THREAD

**Issue by raphink** [prometheus/pushgateway#102]
Currently, the path for pushing is `job/<jobname>/<label>/<labelname>`. This allows for 2 primary keys when updating metrics.

It would be great to allow more than 2 primary keys, by accepting multiple `<label>/<labelname>` levels.

**Comment by raphink** [comment]
Ah, this seems implemented, though undocumented:

https://github.com/prometheus/pushgateway/blob/master/handler/handler_test.go#L406

**Comment by beorn7** [comment]
It's documented here: https://github.com/prometheus/pushgateway#url

**Comment by raphink** [comment]
@beorn7 that's precisely the documentation I was refering to. The example given makes it look like you can add one label and one only. It's not clear that you can have more.

**Comment by beorn7** [comment]
It reads “…followed by any number of other label pairs…”.

**Comment by raphink** [comment]
OK, my bad.
