### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by wujiang** [prometheus/pushgateway#104]
I'm running its dock image on ECS and this error happens periodically:

```
2017/01/24 16:08:59 http: Accept error: accept tcp [::]:9091: accept4: too many open files; retrying in 1s
```

**Comment by beorn7** [comment]
Do you monitor the pushgateway? Could you check what the value of `process_max_fds` and `process_open_fds` is and how it develops over time?

**Comment by wujiang** [comment]
@beorn7 thank you very much for the fast reply. Yes, I can see that `process_max_fds` is 1024. Please see the following image to see how `process_open_fds` developed: 
<img width="1650" alt="screenshot 2017-01-25 11 12 29" src="https://cloud.githubusercontent.com/assets/77030/22298703/78322ec6-e2ef-11e6-8067-f3916c70d2c6.png">

**Comment by beorn7** [comment]
That looks like a fd leak. Most likely you have something pushing to the PGW or scraping it that doesn't properly close the connections. Two things to investigate:
- What can you see with `lsof` and `netstat`? Are there many network connection dangling? Where are they coming from?
- Increase the maximum allowed connection to see if you reach some steady state, or these connections are really ever growing.

**Comment by wujiang** [comment]
Yeah, definitely some fd leak. Thank you for the advice. I'll try to increase the maximum allowed connection and see what happens. 

The PWG receives metrics from some IoT devices and a prometheus server scrapes from it. On these IoT devices, I'm using https://godoc.org/github.com/prometheus/client_golang/prometheus/push to push only counter and gauge to the PWG. Nothing fancy.

**Comment by beorn7** [comment]
How many IoT devices push to the PGW? And how often?

The Prometheus Go client library used the default transport, which sets a keep-alive time of 30s (which helps if a client is pushing more often than once every 30s). Thus, after a push, the connection will be kept open for 30s. My guess is that at that time, something goes wrong. Perhaps your IoT devices change their IP number, and then all the old TCP connections stay dangling? The jumps happen pretty much once per day, which would align with the usual once-per-day-rotate-the-IP-number thing some ISPs do. Each jump is by about 200, which would suggest you have 200 devices pushing.

On a more general note: The PGW is meant to get a handful of metrics pushed. In contrast to the Prometheus server, it was never meant to scale to hundreds or even thousands of targets.

**Comment by beorn7** [comment]
See also https://prometheus.io/docs/practices/pushing/

**Comment by wujiang** [comment]
Understood. Thank you very much for the explanation. I have 10 devices from 3 different locations which are all behind a NAT. They push 3 different events:

1. internet connection checker (every minute 24x7, type `gauge`)
2. device's voltage, ram information (every 5 seconds 24x7, type `gauge`)
3. user activities (triggered by user during daytime, type `counter`)

By monitoring the `process_open_fds`, it looks like it's the 3rd event causing the issue.

<img width="1359" alt="screenshot 2017-01-26 12 04 03" src="https://cloud.githubusercontent.com/assets/77030/22341674/b25ccb6c-e3bf-11e6-8029-327f4dbc8df4.png">

**Comment by beorn7** [comment]
You need to explore the exact nature of the open fd's with the usual means (`lsof`, `netstat`) to proceed with the investigation.

**Comment by wujiang** [comment]
`lsof` returns a list of these (over 2500)

```
1       /bin/pushgateway        socket:[130996896]
1       /bin/pushgateway        socket:[130997427]
1       /bin/pushgateway        socket:[130998606]
1       /bin/pushgateway        socket:[130999669]
1       /bin/pushgateway        socket:[131001674]
1       /bin/pushgateway        socket:[131001022]
1       /bin/pushgateway        socket:[131012006]
1       /bin/pushgateway        socket:[131015348]
1       /bin/pushgateway        socket:[131058466]
1       /bin/pushgateway        socket:[131012909]
1       /bin/pushgateway        socket:[131006459]
1       /bin/pushgateway        socket:[131019350]
1       /bin/pushgateway        socket:[131015399]
1       /bin/pushgateway        socket:[131015989]
1       /bin/pushgateway        socket:[131016775]
1       /bin/pushgateway        socket:[131032853]
1       /bin/pushgateway        socket:[131055026]
1       /bin/pushgateway        socket:[131027605]
1       /bin/pushgateway        socket:[131030977]
1       /bin/pushgateway        socket:[131030979]
1       /bin/pushgateway        socket:[131060294]
1       /bin/pushgateway        socket:[131057040]
1       /bin/pushgateway        socket:[131058096]
1       /bin/pushgateway        socket:[131057403]
1       /bin/pushgateway        socket:[131060123]
1       /bin/pushgateway        socket:[131060245]
1       /bin/pushgateway        socket:[131065567]
1       /bin/pushgateway        socket:[131062432]
1       /bin/pushgateway        socket:[131060474]
1       /bin/pushgateway        socket:[131061845]
1       /bin/pushgateway        socket:[131067155]
1       /bin/pushgateway        socket:[131063727]
```

`netstat` returns a lot of these (over 2500)

```
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:46012 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:47090 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:48774 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:49014 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:35450 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:46248 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:43826 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:38236 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:36722 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:35470 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:35742 ESTABLISHED 1/pushgateway
tcp        0      0 ::ffff:172.17.0.4:9091  ::ffff:108.60.150.203:40432 ESTABLISHED 1/pushgateway
```

**Comment by beorn7** [comment]
That's a lot of established connections to one IP number. I assume that's the one your NAT is setting as source?

For some reason, those connections are never closed. That's either a networking problem (which you have to debug on your side), or it's hanging somewhere in the code of the Pushgateway or the client. An error in the code is unlikely, if you are not doing something weird (like pushing gigantic amount of metrics). You could check the goroutine dump to find if goroutines are blocked on something. (For the Pushgateway:
http://172.17.0.4:9091/debug/pprof/goroutine?debug=2 . For the clients, it depends on the client.)

**Comment by wujiang** [comment]
Yeah, it's the IP from one of the NAT.

The debug url is very convenient. Thank you. I saw a lot of these:

```
goroutine 6351324 [IO wait, 59 minutes]:
net.runtime_pollWait(0x7f9b478db380, 0x72, 0xab4)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42151e920, 0x72, 0xc424b497a0, 0xc42000a200)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42151e920, 0xa17280, 0xc42000a200)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42151e8c0, 0xc423002000, 0x1000, 0x1000, 0x0, 0xa17280, 0xc42000a200)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420143e20, 0xc423002000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
net/http.(*connReader).Read(0xc420ed24e0, 0xc423002000, 0x1000, 0x1000, 0xc424b49908, 0x84cc69, 0x19)
	/usr/local/go/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc422d92c00)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadSlice(0xc422d92c00, 0xa, 0x0, 0x1e, 0xa, 0x33, 0x0)
	/usr/local/go/src/bufio/bufio.go:330 +0xb5
bufio.(*Reader).ReadLine(0xc422d92c00, 0xc423b2d860, 0xf0, 0xf0, 0x8345e0, 0x5d1553, 0xa67808)
	/usr/local/go/src/bufio/bufio.go:359 +0x37
net/textproto.(*Reader).readLineSlice(0xc4225bb7a0, 0xc424b49a98, 0xc424b49a98, 0x4167e8, 0xf0, 0x8345e0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x5e
net/textproto.(*Reader).ReadLine(0xc4225bb7a0, 0xc423b2d860, 0xc, 0x0, 0x43109c)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc422d92c00, 0xc423003000, 0xc423b2d860, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:793 +0xa5
net/http.(*conn).readRequest(0xc4216ab680, 0xa1ab40, 0xc421f79e80, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:765 +0x10d
net/http.(*conn).serve(0xc4216ab680, 0xa1ab40, 0xc421f79e80)
	/usr/local/go/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

Might be some bug from Go.

**Comment by beorn7** [comment]
Unlikely. The above simply means that the socket is still open and the Pushgateway is waiting for more data to come in. That would be consistent with the theory that the network connection was changed (like the NAT switched to a different public IP number during a push or during the keepalive period) and left the existing TCP connections dangling. (They will time out eventually, but the timeout is pretty long, so open FDs accumulate.)

The other possibility is that your clients, for some reason, stop sending data without closing the TCP connection.

In any case, it's unlikely this is a bug in the Pushgateway. (And we are not going to add sophisticated strategies against connection flooding into the Pushgateway.) You have to investigate your network and/or your clients. I'm closing this issue now. Please re-open if you have new evidence it is a bug in the Pushgateway.

**Comment by wujiang** [comment]
understood. thank you!

**Comment by wujiang** [comment]
Just a follow up: the problem might be because some of the devices were restarting quite often. After fixing that, the number of open files is dropping.

**Comment by Subayai** [comment]
This issue has come up repeatedly and as seen at multiple clients implementing Go-lang, seems to be related to this:
[](https://hackernoon.com/avoiding-memory-leak-in-golang-api-1843ef45fca8
)

In any case, the server (Push Gateway) should be resilient to (any) client behavior such that resources do not leak over time as shown. Suspect a custom implementation (versus default) of Go-lang library for HTTP connection management will solve problem (unless default impl library has been fixed in some release and can be looped back into an update of this Go-lang based push gateway).

**Comment by beorn7** [comment]
No, the Pushgateway is not designed to be resilient to misbehaving clients. Surely, we could introduce a configurable shorter timeout to close idle connections. But that's just one attack vector. A misbehaving client could as well push way to much data and crash the Pushgateway. So we needed to introduce a configurable limit of metrics being pushed. And so on… The Pushgateway would (d)evolve into a monster of complexity with dozens of levers to adjust if we wanted to go down that road. We deliberately decided that the Pushgateway depends on well behaving and trusted clients.
