### ISSUE TITLE
Provide a HTTP Health Check

### ISSUE THREAD

**Issue by iksaif** [prometheus/pushgateway#105]
Kubernetes, Marathon, consul and others require health checks, and often an HTTP based one. While Prometheus and Alertmanager can somewhat use their status page this is quite painful with pushgateway because it contains all the metrics that have been pushed to it.

Could we consider adding either a separate light status page or a dedicated /health endpoint ?

**Comment by beorn7** [comment]
That's a good point. Personally, I don't have much experience with running those stateful Prometheus components on Kubernetes, so I didn't really run into it myself.

@fabxc what's your take on this topic? You and your CoreOS colleagues should be much more directly affected. Would it be a good idea to provide a dedicated health endpoint on all our components? This could involve some real health checking where appropriate (which is something the status page doesn't provide).

**Comment by jsravn** [comment]
This would be really useful. Our status page is 6M (don't ask why! :)) and the metrics endpoint is 2M. This means we need quite long probe timeouts.

**Comment by beorn7** [comment]
Pinging @fabxc again (as I want to implement this in a way that will be useful across components of the project, not just for this special case).
@fabxc : How do you do health checking for Prometheus components in K8s so far? How do you do liveness vs. readiness probes? Should we perhaps support both with an endpoint?

**Comment by fabxc** [comment]
Currently we also hit `/status` on Prometheus and check for 200.
A dedicated health endpoint would probably be good. Can just return 200 initially but it will enable use to add some internal checks under the hood later.

That'd be liveness probe.

Readiness could be added, e.g. waiting for Prometheus to load the initial checkpoint. But I'd only add endpoints once we have something to actually check. Other components probably don't have such a condition.

**Comment by beorn7** [comment]
Currently, Prometheus doesn't serve any HTTP while loading the checkpoint (or worse: running crash recovery). Definitely something to think about.

Are there established conventions for the path of those liveness/readiness endpoints?

**Comment by fabxc** [comment]
Kubernetes components use /healthz for reasons you can imagine. In general
there are no defaults or conventions beyond that.

**Comment by beorn7** [comment]
I'm _soooo_ tempted to use `/livenezz` and `/readinezz` now… :)

If there are no conventions yet, I'd suggest `/health` and `/readiness` (nouns) or `/healthy` and `/ready` (adjectives).

Another line of thought would be to use special prefixes like the `/debug/...` for Go profiling and expvar or the `/-/health` pattern often used. That would be for easy filtering of non-public endpoints. Prometheus components are all meant to be internal anyway, but it might help to stick to conventions other HTTP services have.

**Comment by brian-brazil** [comment]
I've seen /healthy used in non-k8 systems.

I must admit I'm tempted by /livenezz and /readinezz.

**Comment by beorn7** [comment]
I'll create a PR soon-ish for PGW (where things are small and easy). If we like it, we can propagate the pattern to the bigger components.

**Comment by iksaif** [comment]
Why not just /health and /live ?

Le 2 mars 2017 14:40, "Björn Rabenstein" <notifications@github.com> a
écrit :

**Comment by beorn7** [comment]
health and live would both refer to liveness (i.e. if this is not OK, restart me).
Readiness is a different thing (if it's not OK, it means: "I'm loading or recovering, please don't kill me but don't send me traffic yet").

**Comment by beorn7** [comment]
It might just be my OCD, but "health" is a noun, and "ready" is an adjective, while "healthy"/"ready" are both adjectives and "health"/"readiness" are both nouns.

**Comment by iksaif** [comment]
The idea is that you do GET /health, which makes sense. I might also be
used to /healthz and quote biased.

Le 2 mars 2017 6:19 PM, "Björn Rabenstein" <notifications@github.com> a
écrit :

**Comment by matthiasr** [comment]
What would be the downsides of using readinezz and livenezz? As long as they're documented, it doesn't really matter what the letters are. These two are least likely to conflict with anything else we might want to do; and being a bit silly is okay as long as it gets the job done IMO 😃

**Comment by beorn7** [comment]
Another point: the reload endpoint in the Prometheus server is `/-/reload`. Arguably, this is so that you don't hit it accidentally. `/-/` could also be seen as an administrative prefix.

**Comment by matthiasr** [comment]
Ah, if we're already using /-/ we should continue to do so, or stop completely, for consistency. I am in favour of sticking this under /-/.

**Comment by grobie** [comment]
+1 for consistency
+1 for standard english names (health > healthz)

**Comment by rajendrakumara** [comment]
Hi 
When can we expect separate health check endpoints /health on prometheus. Thanks

**Comment by beorn7** [comment]
This issue is about Pushgateway.

However, eventually we want the same endpoints on all components in the Prometheus ecosystem. This issue just evolved into the prototype, but where to implement it first doesn't really matter.

The bottom line I see from the discussion so far is `/-/healthy` and `/-/ready` as endpoints. The only technical complication I see is that `/-/healthy` should essentially return a 200 as soon as possible after startup while currently Prometheus (and possibly other components) only binds to the HTTP port when it is ready to operate (i.e. after checkpoint loading and such). With this in mind, anybody could come up with a PR.

**Comment by aequasi** [comment]
Any update on this? Been afew months

**Comment by iksaif** [comment]
Ok, I'll try to work on it for realz. @beorn7  do you think the implementation should be somewhat shared or it's ok for each component to have their handlers for now (and we can refactor later) ?

Also, I guess that as a start, it's ok to have `/-/healty` and `/-/ready` just return 200 as soon as we can listenandserv, and try to make that better later. This will at least fix the current issue which is that there is no handler usable for marathon/kube/consul.

**Comment by iksaif** [comment]
Ok, gave it a try in https://github.com/prometheus/pushgateway/pull/135
