### ISSUE TITLE
Redis as a persistent storage

### ISSUE THREAD

**Issue by Pluto1010** [prometheus/pushgateway#111]
Hello,

I've heard that entries in the DiskMetricStorage won't expire and so the storage grows endlessly. 

What about storing all data to Redis? It supports some kind of persistence and KV pairs can have an expire time. This way no one has to reinvent such features again.

I would like to hear your thoughts about this.

Have a nice day,
Dennis

**Comment by beorn7** [comment]
Users are supposed to delete or overwrite entries in a controlled fashion.

Implementing an expiration time wouldn't be that big of a deal (probably less effort than implementing a Redis integration, not to speak about the additional operational overhead). However, this feature has been requested and subsequently rejected multiple times: #83 #19 

Please let me know if you have new evidence to present that would warrant reopening the debate.
