### ISSUE TITLE
Security while pushing into PushGateway

### ISSUE THREAD

**Issue by mohanprasaths** [prometheus/pushgateway#118]
Guidance needed . Thanks in advance
How can I apply some security while posting/pushing data into PushGateway? 

>ie: the pushgateway should accept data only from authenticated post/put message .

Should I  be writing my own **middleware** ?

**Comment by brian-brazil** [comment]
Usage questions should be asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users
