### ISSUE TITLE
Pushgateway delete issue

### ISSUE THREAD

**Issue by Ajeyprabhu** [prometheus/pushgateway#128]
Hi .. Am trying to delete using the below command syntax. The response is 202 But the data doesnt get deleted. Please advise. 

 curl -X DELETE http://pushgateway.example.org:9091/metrics/job/some_job

**Comment by beorn7** [comment]
I need more data to verify if this is really a bug. I suspect it's a usage mistake. Could you bring this to the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) together with precise information about what metrics you have pushed how, and which metrics you expect to get deleted. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

In the unlikely case that the conclusion is that you have hit a bug, we can re-open this issue.

**Comment by Ajeyprabhu** [comment]
Thank you Bjorn .. I have put it with more details in groups. ..
