### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by powersj** [prometheus/pushgateway#131]
On a couple of occasions, the web interface will stop loading all metrics and hang. If I examine the logs I see a: "runtime error: invalid memory address or nil pointer dereference" message. For the full panic see:

https://paste.ubuntu.com/25447731/

If I stop the service, mv the persistence file, and start the service again everything resumes as expected:

time="2017-09-01T22:55:05Z" level=info msg="Metrics persisted to '/var/lib/prometheus/pushgateway.data'." file=diskmetricstore.go line=156 
time="2017-09-01T22:56:25Z" level=info msg="Received SIGINT/SIGTERM; exiting gracefully..." file=main.go line=132 
time="2017-09-01T22:56:25Z" level=info msg="HTTP server stopped: accept tcp [::]:9091: use of closed network connection" file=main.go line=105 
pushgateway, version 0.2.0+ds (debian/sid, commit 0.2.0+ds-3)
  build user:       pkg-go-maintainers@lists.alioth.debian.org
  build date:       20160125-23:49:58
time="2017-09-01T22:56:44Z" level=info msg="Listening on :9091." file=main.go line=98 
time="2017-09-01T23:01:44Z" level=info msg="Metrics persisted to '/var/lib/prometheus/pushgateway.data'." file=diskmetricstore.go line=156 

Running on Ubuntu 16.04 (xenial) with version 0.2.0+ds-3.

**Comment by beorn7** [comment]
Thanks for the report.

Since there are bugfixes in the storage layer after 0.2, this particular issue might very well be fixed in the current version. 0.4.0 is already in debian/sid, AFAIK. Could you upgrade and check if this is still happening?

**Comment by powersj** [comment]
I've upgraded and will monitor it over the next few days. If it comes back I will re-open this. Thanks!
