### ISSUE TITLE
Docker Hub information is outdated

### ISSUE THREAD

**Issue by pmoranga** [prometheus/pushgateway#139]
The information on https://hub.docker.com/r/prom/pushgateway/ is outdated.

As example the default binding port and extra new parameters accepted by the binary.

**Comment by beorn7** [comment]
Thanks for flagging. 

I had naively assumed the description would auto-update from the README.md. That's not the case, so maintaining the description separately is asking for inconsistencies. I replaced it by a pointer to the GH repo.
