### ISSUE TITLE
Pruning Pushgateway stale metrics - Sidecar to Pushgateway

### ISSUE THREAD

**Issue by DonMartin76** [prometheus/pushgateway#145]
Hi,

This may not actually be an issue, but I wanted to ask whether a link to our project `pushgateway-pruner` might be interesting: https://github.com/Haufe-Lexware/pushgateway-pruner

It's intended to be deployed as a sidecar to Pushgateway, and it checks the `push_time_seconds` for metrics which have not been updated since a specific amount of seconds (threshold). I'm horribly sorry it's not written in go, but in node. The image is still smallish (80 MB).

We're using the pushgateway to collect metrics from monitoring systems which run outside the actual application, and which then push in the metrics. If we deploy new versions of the monitoring containers, the instance label changes (which is what we want), and we run into the stale metrics issue. I could imagine other people would also have use for this kind of thing.

Feel free to just close this issue, or to decide whether you want me to create a PR against the docs here with a link to our pruner.

Cheers,
Martin

**Comment by brian-brazil** [comment]
This is not a recommended way to use the pushgateway, see https://prometheus.io/docs/practices/pushing/

**Comment by DonMartin76** [comment]
:-D I am very well aware of that. But it works, and I don't see many other ways of implementing my use cases which don't mean I get multiple Prometheus instances and/or complex network tunneling scenarios. Like this, I get the metrics into the production prometheus instance, more or less like if the monitoring containers ran inside the same cluster.

**Comment by brian-brazil** [comment]
This feature has been rejected by this project, and I don't think we should be endorsing other ways of doing the same thing.

**Comment by DonMartin76** [comment]
OK, it's up to you to decide that (which is why I opened this ticket).

I still think it's a valid use case for the Pushgateway - getting metrics in from the outside, as long as you can protect the Pushgateway end point via some kind of authorization (in our case we've put it behind an API Management component).

Thanks for your input!

**Comment by hairyhenderson** [comment]
@DonMartin76 FYI - there are alternatives that may or may not be more suited to your use-case - see [torch](https://github.com/outbrain/torch), [pushprom](https://github.com/messagebird/pushprom), or even [statsd_exporter](https://github.com/prometheus/statsd_exporter)

**Comment by pokerazor** [comment]
We built a small tool which may also be helpful in the context: https://github.com/KuguHome/prometheus-metrics-retoucher
