### ISSUE TITLE
get error "text format parsing error in line 2: unknown metric type "counter\r"" when try to push using ARC

### ISSUE THREAD

**Issue by 08s011003** [prometheus/pushgateway#147]
I try to push metrics to gateway using ARC. My url in ARC Request is as following:

 

>
POST/metrics/job/some_job/instance/some_instance HTTP/1.1
HOST: myip:9091
accept: text/plain
accept-encoding: gzip, deflate
accept-language: en-US,en;q=0.8
user-agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
x-tenant-name: default
content-type: text/plain
content-length: 229

\# HELP http_requests_total The total number of HTTP requests.
\# TYPE http_requests_total counter
http_requests_total{method="post",code="200"} 1027 1395066363000
http_requests_total{method="post",code="400"}    3 1395066363000

> 

I got error 

> 
text format parsing error in line 2: unknown metric type "counter\r"
> 

What does it matter with this error?

**Comment by brian-brazil** [comment]
You should use a client library to push your metrics to ensure you are using the correct format. Here it appears you are using DOS rather than UNIX line endings. Make sure you are using \n rather than \r\n.

**Comment by brian-brazil** [comment]
Also, https://prometheus.io/docs/practices/pushing/

**Comment by beorn7** [comment]
UNIX line ending is required for pushing. That's by design.
