### ISSUE TITLE
Update CircleCI configuration to 2.0 format

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#148]
CircleCI 1.0 will be shut down on August 31. [Resources](https://circleci.com/sunset1-0/)

Template to work off: prometheus/node_exporter#844

**Comment by hairyhenderson** [comment]
I was about to take this on, but then realized that CircleCI builds seem not to run during forked PRs. Can this be enabled? There's a separate setting in CircleCI for passing secrets to forked builds, so I think there shouldn't be a security issue.

**Comment by beorn7** [comment]
Thanks for pointing that out. I have enabled builds for PRs from forks now.
