### ISSUE TITLE
Move to common/route package

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#149]
https://github.com/prometheus/common/tree/master/route is most likely applicable to the Pushgateway, too. Note the discussion in #146 about caveats. Also, see https://github.com/prometheus/prometheus/issues/4004 .

**Comment by beorn7** [comment]
Now also note https://github.com/prometheus/prometheus/pull/4256 . I'm confused now what the flag means for the Prometheus server. This needs clarification.

**Comment by beorn7** [comment]
To learn about the meaning of `--web.external-url` and `--web.route-prefix`, see @brian-brazil 's helpful blog posts
- https://www.robustperception.io/using-external-urls-and-proxies-with-prometheus/
- https://www.robustperception.io/external-urls-and-path-prefixes/

My understanding so far is that we don`t need `--web.external-url` as we only ever work with relative paths. But for one, I might be wrong, and even if I'm right, this might change eventually.

**Comment by brian-brazil** [comment]
Route prefix is still needed to handle where there's a prefix on the incoming http requests that's not the same as on the external-url. External URL is required as the HTML uses absolute paths.

**Comment by beorn7** [comment]
I think that's what I said, no?

**Comment by brian-brazil** [comment]
I interpreted it as you saying external-url was not needed, but you were unsure. I said that we do need external-url with the current codebase.

**Comment by beorn7** [comment]
So you are saying my assumption that PGW only uses relative paths is wrong?

**Comment by brian-brazil** [comment]
Yes, from the current html:

```
    <script src="/static/functions.js"></script>
```

**Comment by beorn7** [comment]
Hmm, but we are not using the host name anywhere, do we? Shouldn't we then be fine with the route-prefix?

**Comment by brian-brazil** [comment]
The slash at the start makes it absolute, without that slash it'd be okay. Otherwise the JS won't load if the browser is using a different prefix to what the pushgateway is configured for.

**Comment by beorn7** [comment]
I think I got it now.

I have still conflated the route-prefix implementation currently in the PGW with the one in the Prometheus server. The former is essentially external-url, but without the host and schema part (as we don't need that one), while the latter doesn't exist in PGW (but would be required to handle the case where the reverse proxy rewrites paths).

With all that confusion, I'm thinking what is actually keeping us from making all paths relative, at least in the PGW, and get rid of the whole prefix and external url stuff altogether?

**Comment by brian-brazil** [comment]
You can switch to relative paths, however you'd still need the route prefix if you want to support those who wish to serve things behind a reverse proxy that preserves prefixed paths such as requested in #73.

There is a consistency argument that you should support both flags so things will work the same as Prometheus/AM which has the default route prefix coming from the external url.

**Comment by beorn7** [comment]
I have fixed `--web.external-url` and `--web.route-prefix` by now. While doing it, I came to the conclusion that adopting the common/route package would be overkill for the specific niche the PGW is in.

I'll close this, but if somebody disagrees and feels like doing the work of incorporating `common/route` here (and feels confident it is the right way), feel free to re-open (or poke me to re-open).

**Comment by brian-brazil** [comment]
I'm currently thinking we'll put the external url stuff in with the TLS stuff when that makes it to common. It's in ~4 places by now.
