### ISSUE TITLE
io.prometheus.client.exporter.PushGateway.doRequest Authentication Enhancement

### ISSUE THREAD

**Issue by cluttazi** [prometheus/pushgateway#159]
Hello,
We currently have prometheus behind a NGINX server, and we are trying to do a basic authentication using the PushGateway class. We are passing the credentials using username:password@host inside the PushGateway constructor, however the credentials are not used in the server.
Is this an issue or should we handle the credentials in another way?
I can see the code for io.prometheus.client.exporter.PushGateway.doRequest could add the credentials, what do you guys think?

Thanks, kind regards,
CL.-

**Comment by DigasNikas** [comment]
+1

**Comment by beorn7** [comment]
This sounds like you are talking about the client library ( https://github.com/prometheus/client_java I assume ). Or is there anything you need changed in the Pushgateway itself? (You filed this issue in the repo for the Pushgateway itself, not for the client library.)

**Comment by cluttazi** [comment]
Close because of dup with https://github.com/prometheus/client_java/issues/364
