### ISSUE TITLE
Pushgateway GO impl has file-descriptor leak / crashes host

### ISSUE THREAD

**Issue by Subayai** [prometheus/pushgateway#164]
Multiple admins have downloaded and installed the push gateway GO impl on to different OS/platforms.

In every case, after a few days of Prometheus server pulls and client pushes, the server crashes with the logs showing resource exhaustion of file-descriptors as root cause.

Implemented a Java based push gateway for private company implementation of same functionality - has run with same Prometheus server and clients pushing metric bundles for over six months with no issues by matter of comparison in same company environments on same servers, etc to rule out operating system or other factors.

**Comment by beorn7** [comment]
Could you add the output of 

    lsof -p `pgrep pushgateway`

so that we can see what those file descriptors are doing?

**Comment by beorn7** [comment]
Closing for lack of response.

Please follow up if you can provide the requested information.
