### ISSUE TITLE
Consider not assigning an instance label if none is requested

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#18]
Currently, we add the ip number:
https://github.com/prometheus/pushgateway/blob/master/handler/push.go#L55

Cf. https://github.com/prometheus/prometheus/issues/490

**Comment by beorn7** [comment]
Currently, everything in the pushgateway is grouped by job/instance tuples... So not having an instance label needs some thinking. Probably treat an empty instance label as 'no label' (and do not export it in that case) so that all metrics with only a job label are in the same group then.

**Comment by brian-brazil** [comment]
A thought I had: if we do this we could change it so `instance` isn't special and /job/myjob/label/myLabel/ would set `label`. That could also act as a grouping for UI purposes, though I'm not too worried about the grouping/UI overall.

**Comment by beorn7** [comment]
I guess, concluding from other discussions, we should get completely rid of the special role of the instance label and never meddle with the instance label, remove it from the REST API, and don't group by it.

**Comment by beorn7** [comment]
Migration path: Encourage users to not set an instance label. Stop setting one automatically, and group by job only whatever has no instance label. (An instance label set as a 'real' labes, i.e. not via the REST API, could be ignored for grouping... Currently it is _overwritten_...)
Once nobody sets instance labels anymore, we can just remove them completely from the pushgateway and from clients (except as normal labels, of course).

**Comment by grobie** [comment]
Will it be possible for clients to set the instance label in a different way, for example like any other label? What is with use cases where a process can't be scraped (workers where it's unfeasible to start a HTTP server, services behind strict firewalls, etc.), but where an instance label is still desired?

**Comment by beorn7** [comment]
Yes, an instance label would be a label as any other. (With the only distinction that the Prometheus server sets it... but we already discussed to make that configurable, see https://github.com/prometheus/prometheus/issues/490 .)

The important thing is that the pushgateway will not set one on its own, and there will be no grouping by instance labels. DELETE will delete all metrics of a job, and PUT will replace all metrics of a job.

**Comment by grobie** [comment]
Without the option to define a grouping label, it will be very expensive (many HTTP calls), complicated (the client needs to check any previously set label to override it/delete it) and racy (it's possible that the server scrapes the pgw while a client is still doing POST/DELETEs) for multiple instances to push metrics to the pgw under the same job label. Essentially, it means the pushgateway is not longer suitable to act as gateway for multiple instances which can't be scraped and need to push their metrics instead.

While I haven't seen too many examples in the discussion so far - explaining what use cases the instance label prevent or why they are "badly broken" - I understand that it's not desired to apply an instance label automatically even if not set explicitly. What are the use cases to also remove the optional setting of an instance label (or any grouping label for that matter), so that it's easy for multiple instances behind a pushgateway to replace the metrics periodically and independently of each other?

**Comment by beorn7** [comment]
We have to analyze the actual use cases to come to a final conclusion here.

If we really want to support the use case where clients can't expose an HTTP endpoint, we have to find out what the best solution for that is. With the current setup, those metrics wold not be exactly mirrored, as the server would give them `exporter_job` and `exporter_instance` labels, which would make them inconsistent with directly scraped labels.

**Comment by brian-brazil** [comment]
> explaining what use cases the instance label prevent or why they are "badly broken"

They prevent pushing metrics without an instance label, which is the main intended use case of the push gateway - service-level cronjobs. Requiring a instance label leads to users setting one, where they shouldn't leading to misunderstandings of the data model. Putting in an instance label of the pushing host breaks things when the cronjob moves to another machine.

> Will it be possible for clients to set the instance label in a different way, for example like any other label? 

That's what I'd propose. I can see us ending up with convenience functions to provide the current functionality on the client side, as it is unfortunately a not uncommon use case.

**Comment by beorn7** [comment]
I guess, what should improve things in any case, would be the following (as it allows the label-less approach, but doesn't break the "mimic a scrape" approach):

- Pushgateway will cease to auto-create instance labels.

- Grouping will stay as it is, but the "missing/empty instance label" will be its own group. (Note that grouping is not just an UI thing, but determines which metrics to replace upon `POST` and `PUT`.) I also believe we must use only the labels passed in via the REST API for grouping, i.e. if the `POST` or `PUT` URL comes without instance, the metrics will be pushed into the "missing/empty instance label", even if an instance label is attached in the conventional way. (Technical reasons for that: If a grouping instance label is not given via the URL, the Pushgateway has to search each and every metric for instance labels. Not only is that expensive, it also might lead to one push being funneled into more than one job/instance group, which will completely confuse the whole "which metrics to replace" semantics.)

- We will add config options to the Prometheus server to _not_ add instance and/or job labels (so that either a missing label stays missing, or an existing label is not complemented by `exporter_instance` and/or `exporter_job`).

**Comment by brian-brazil** [comment]
> Grouping will stay as it is, but the "missing/empty instance label" will be its own group.

I'd propose that we allow arbitrary labelsets to be passed via the URL, of which instance is just a special case. Replace then only affects metrics with the same group as is passed via the URL.

> We will add config options to the Prometheus server to not add instance and/or job labels 

It's a bit more complicated unfortunately. We also require that the instance label of the pushgateway not appear on these metrics.

**Comment by beorn7** [comment]
Is there a use case for arbitrary grouping? Conceptually, I like the general approach, but it also makes things more complicated to handle and understand, so I'd only like to add it if there is a use beyond aesthetics of the design.

WRT labels added by the Prometheus server: That's what I meant. If we can configure targets to not get instance labels added, they would not get the Pushgateway's instance label, either. (In other word: With that setting, an instance label already set would be left alone, but an empty/missing instance label would also be honored, i.e. it would be left missing.)

**Comment by brian-brazil** [comment]
> Is there a use case for arbitrary grouping?

Consider say a system that was sharded and you wanted to track a cronjob for each shard. Having a shard label in addition to job would be very useful, rather than having to do job_shard in the job label. 

> (In other word: With that setting, an instance label already set would be left alone, but an empty/missing instance label would also be honored, i.e. it would be left missing.)

How would that distinguish from the push_gateway's own metrics?

**Comment by beorn7** [comment]
I see... So I guess the "how to not apply an instance label" is a bigger story then...

**Comment by brian-brazil** [comment]
My thought was to export {instance=""}

**Comment by beorn7** [comment]
That might work. Although we are running in the interesting fine point when an empty label is equivalent to an unset label and when not... https://github.com/prometheus/prometheus/issues/494

**Comment by brian-brazil** [comment]
Yeah, it's overloading a bit but this'd only apply to the exposition format.

We'll need to handle it in the exposition format one way or the other.

**Comment by beorn7** [comment]
OK, 2nd try for sketching out a plan:

**Step 1:** Change Pushgateway's behavior to add an empty instance label when no instance label or an empty instance label is given.

Implications:
- As job labels, any instance labels in the pushed metrics will always be overridden according to the POST/PUT URL (even the instance label is missing in the URL, it will then set to instance="" in the pushed metrics).
- Grouping will (for now) stay the same, just that instance="" is a valid instance to group for (display wise, it should probably be shown as "no instance label").
- The DELETE semantics will change: DELETE a job without an instance label will delete all the metrics of that job with an _empty_ instance label (rather than all metrics with the job).

**Step 2:** Change the Prometheus server's behavior to have a "honor labels" mode where it will not add "exporter_..." labels if job/instance metrics are already given (even if they are empty).

**Step 3.** Generalize grouping as described above.

That needs a changed (or adding an alternate) REST API with a "groupby" verb or something, where arbitrary labels can be given. Those labels will all be enforced in the pushed metrics.

**Comment by brian-brazil** [comment]
I think we need a step first with the new go-level API without an instance argument, a way to pass labels as a map (initialling only supporting instance) and a convenience function to use provide $HOSTNAME as the instance.

Then existing users who want the instance label can switch to that, and then we can fix the rest under the covers.

**Comment by grobie** [comment]
> The DELETE semantics will change: DELETE a job without an instance label will delete all the metrics of that job with an empty instance label (rather than all metrics with the job).

What is the motivation for that change? I don't think we'll have use cases where for the same job label, some instances will set a grouping label and others are not. I can only imagine it's no one sets a group by label (pure application metrics) or everyone sets it (instances which can't be scraped). So it might be easier to understand the API if we keep the current semantics? I'm probably missing something here though.

**Comment by grobie** [comment]
Disregard my last comment, I see now that this implication is unavoidable.

**Comment by beorn7** [comment]
I guess we have reached some kind of convergence. I'm going to file issues in the various repos to put our plan into action.

**Comment by beorn7** [comment]
I updated https://github.com/prometheus/prometheus/issues/490 so that it covers our discussion here.

**Comment by beorn7** [comment]
Working on this right now.

I plan to not treat empty instance label as special. Essentially, if an instance label does not make sense, the user will not push an instance label, and no instance label will be exported.

We then need to have a suitable config option on the Prometheus server side to allow targets that do not get an instance label attached.

**Comment by brian-brazil** [comment]
That doesn't sounds quite right, as the pushgateway itself will still have an instance label for it's own metrics.

Do we need to extend the exposition formats to support this?

**Comment by beorn7** [comment]
@brian-brazil Ouch... yeah, thanks for reminding me... That was the problem we discussed earlier... So yeah, I guess we want an empty label value being meaningful in the exposition format. So "no instance label" needs to translate into `instance=""`...

**Comment by brian-brazil** [comment]
I was thinking we'll probably want a flag on the pushgateway for which labels to treat specially, defaulting to just instance.

Then a scrapeconfig option for which targets to trust the labels on, rather than add `exporter_`

**Comment by beorn7** [comment]
We require to always have a `job` label in metrics pushed to the Pushgateway. So the only label we need to handle specially is `instance`, and the only special treatment is that a missing instance label will be added as `instance=""`.

I guess we can easily put the set of labels handles specially in that way into a flag. (Can't really think of a use case right now, but as there can be other labels the server treats by prepending `exporter_` (global labels, additional per-target labels), it might come up...

And yes, as https://github.com/prometheus/prometheus/issues/490 describes, we need that `honor-labels` config option for targets in the server.
