### ISSUE TITLE
processWriteRequest overwrites the metrics in metricFamily

### ISSUE THREAD

**Issue by viralkamdar** [prometheus/pushgateway#186]
storage/discmetricstore.go:processWriteRequest() overwrites the existing metrics in a group for an already existing metricfamily. Ideally it should merge the new metrics with the existing ones.

**Comment by beorn7** [comment]
That's the behavior documented [here](https://github.com/prometheus/pushgateway#post-method), isn't it?

The Pushgateway by design never merges metrics. Either the whole group is replaced (`PUT`) or the whole metric family (AKA metrics with the same name) are replaced (`POST`).

**Comment by viralkamdar** [comment]
Ok.. I misunderstood
