### ISSUE TITLE
Add/modify route-prefix and external-url flags to work the same as for the Prometheus server

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#190]
Details are discussed in #149 . This issue is meant to track the (more urgent) user-facing behavior (in contrast to implementation details of the routing).

In short: `--web.route-prefix` should work in the same way as for the Prometheus server. `--web.external-url` should be added with the same semantics as for the Prometheus server.

**Comment by clausa20** [comment]
+1

**Comment by shinhwagk** [comment]
+1

**Comment by kinghuang** [comment]
Is the `--web.route-prefix` option on pushgateway 0.7.0 supposed to work? I've configured it like I do for Prometheus, but it's not serving up CSS and JS resources correctly.

I currently have `--web.route-prefix=/pushgateway`. And, main page returned by pushgateway reflects this in the CSS and JS paths, but it's returning 404 for all of them.

```
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Prometheus Pushgateway</title>
    <script src="/pushgateway/static/jquery-2.1.4.min.js"></script>
    <link rel="stylesheet" href="/pushgateway/static/bootstrap-3.3.4-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/pushgateway/static/bootstrap-3.3.4-dist/css/bootstrap-theme.min.css">
    <script src="/pushgateway/static/bootstrap-3.3.4-dist/js/bootstrap.min.js"></script>
    <script src="/pushgateway/static/functions.js"></script>
    …
```

**Comment by beorn7** [comment]
That seems messed up, too. I'll declare this now to be a bug, too. :o(
