### ISSUE TITLE
An error has occurred during metrics collection:500 internal server err

### ISSUE THREAD

**Issue by SKRVulupala** [prometheus/pushgateway#191]
When I am trying to use Pushgateway (c#) to publish metrics, I get below err

> 

2 error(s) occurred:
* gathered metric family process_start_time_seconds has help "**Start time of the process since unix epoch in seconds**" but should have "**Start time of the process since unix epoch in seconds.**"
* gathered metric family process_cpu_seconds_total has help "**Total user and system CPU time spent in seconds**" but should have "**Total user and system CPU time spent in seconds.**"

> 

In my prometheus localhost:9090 dashboard I see the status as 500 intrnl err

http://localhost:9091/metrics | DOWN | instance="localhost:9091" | 581ms ago | server returned HTTP status 500 Internal Server Error
 
-- I cloned and checked in the code (**DotNerStatsCollector.cs**) class I saw

            _startTime = metrics.CreateGauge("process_start_time_seconds", "Start time of the process since unix epoch in seconds");
            _cpuTotal = metrics.CreateCounter("process_cpu_seconds_total", "Total user and system CPU time spent in seconds");

here the arguments dont have period in the end !!!!!
So, is period the culprit ??? Am I running uncompatable versions ? is it a bad unit test ???

how to pass through this issue.

**Comment by SKRVulupala** [comment]
I tried forking the code and added the period 
            // Metrics that make sense to compare between all operating systems
            _startTime = metrics.CreateGauge("process_start_time_seconds", "Start time of the process since unix epoch in seconds.");
            _cpuTotal = metrics.CreateCounter("process_cpu_seconds_total", "Total user and system CPU time spent in seconds.");

which essentially cleared the error I was struck with !!! Do you want me to req a PR for the change or are you gonna fix the unit test ?????

**Comment by beorn7** [comment]
Yes, that's a bug. However, it is not in the Pushgateway code but in https://github.com/stefanprodan/prometheus.aspnetcore . I suggest to create a PR against that repository.

I'm closing this issue as it has nothing to do with the Pushgateway code.
