### ISSUE TITLE
Fix inconsistent HELP string across groups

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#194]
Currently, if two metrics of the same name but with different HELP are pushed into the same group, the Pushgateway will notice and pick one HELP message over the other (and spit out a warning about it).

However, if the metrics are pushed to different groups, the Pushgateway won't notice, but then the code coming from client_golang will block the exposition as inconsistent HELP string cannot be rendered in the Prometheus exposition format.

Since inconsistent HELP strings are even more likely across groups, the same fix should be applied. (Similar might be relevant for TYPE.)

**Comment by beorn7** [comment]
Looking at #196, it seems that even within the same group, the HELP string is not fixed, but merely warned about in a slightly better way. Scraping still fails.

I think if the TYPE is inconsistent, there is nothing we can do (as this might result in very different treatment of the metric family during exposition, cf. `Histogram` vs. `Counter`. However, inconsistencies in the HELP string are just happening too often, thus picking one string to have priority (and warn about it) seems good enough.

**Comment by majorinche** [comment]
@beorn7 hello, so how to fix this problem, i meet the similar problem
it happens only when i tried to push tidb/pd/ metrics to pushgateway side

An error has occurred during metrics collection:

gathered metric family go_memstats_sys_bytes has help "Number of bytes obtained by system. Sum of all system allocations." but should have "Number of bytes obtained from system."

**Comment by beorn7** [comment]
From the user's side, this can only be fixed by making sure all pushers use the same HELP strings for the same metric name, i.e. in your case, you needed to update all pushers to the same version of the Prometheus Go client library.

The fix suggested by this Github issue has to be done in the code of the Pushgateway.

**Comment by beorn7** [comment]
As another work-around, you could just run more Pushgateways so that one and the same Pushgateway will not receive inconsistent metrics anymore.

**Comment by jkschneider** [comment]
> I think if the TYPE is inconsistent, there is nothing we can do (as this might result in very different treatment of the metric family during exposition, cf. Histogram vs. Counter. 

👍 👍 

> However, inconsistencies in the HELP string are just happening too often, thus picking one string to have priority (and warn about it) seems good enough.

Do you think warn once per metric name and then be silent is OK? Selfishly, I fear that consistent log warnings on every push are still going to generate lots of questions for Micrometer for something that Micrometer really can't do anything about.

**Comment by beorn7** [comment]
On the other hand, if it is a "real" name collision, where two metrics that mean something completely different, happen to end up with the same name and on the same Pushgateway, you have a real problem because one of those metrics will now have a seriously misleading HELP string. I'd rather err on the "too much logging" side here.

In different news, I think if you push any go_... or process_... metrics to the Pushgateway, you are probably doing something wrong anyway. Cf. https://prometheus.io/docs/practices/pushing/

**Comment by jglapa** [comment]
Hi so I'm also affected by this. 
I have the pushgateway up and running (docker `latest`) and it works fine with `prometheus-node-exporter` bundled with Ubuntu 16.04 apt package (AFAIK v0.11 of the exporter). 
But once I start pushing metrics from servers that are running Ubuntu 18.04 (v0.16). I'm getting this:
```
gathered metric family go_memstats_sys_bytes has help "Number of bytes obtained by system. Sum of all system allocations." but should have "Number of bytes obtained from system."
```

**Comment by jglapa** [comment]
Hi @beorn7 I've upgrade my `prometheus-pushgateway` to `v0.6.0` and pushed something from Ubuntu18. And now I'm getting this error:
```
204 error(s) occurred:
* collected metric "node_netstat_IpExt_InOctets" { label:<name:"instance" value:"db-mec" > label:<name:"job" value:"push-gateway" > untyped:<value:5.15580861661e+11 > } is not a GAUGE
* collected metric "node_netstat_Icmp_OutRedirects" { label:<name:"instance" value:"db-mec" > label:<name:"job" value:"push-gateway" > untyped:<value:0 > } is not a GAUGE
....
```

**Comment by beorn7** [comment]
Yeah, that's about the type. You have already pushed _gauges_ named node_netstat_IpExt_InOctets and node_netstat_Icmp_OutRedirects, but then also pushed metrics of the same name with type _untyped_. Ideally, one of them is just a leftover, and you can simply delete it via the web UI or the DELETE REST call.

If you have two different pushers pushing metrics of the same name but different type, you have to bring them in line with each other or use a different PGW for each.

**Comment by jglapa** [comment]
ok, so it now comes down to the `prometheus-node-exporter` generating those incorrectly. How come this works fine with the normal way to running this ( prometheus scraping them)

`prometheus-node-exporter (v0.11)`
```
ubuntu@ubuntu16:~$ curl -s http://localhost:9100/metrics  | grep node_netstat_IpExt_InOctets
# HELP node_netstat_IpExt_InOctets Statistic IpExtInOctets.
# TYPE node_netstat_IpExt_InOctets untyped
node_netstat_IpExt_InOctets 5.41694886709e+11
```

`prometheus-node-exporter (v0.15)`
```
ubuntu@ubuntu18:~$ curl -s http://localhost:9100/metrics  | grep node_netstat_IpExt_InOctets
# HELP node_netstat_IpExt_InOctets Statistic IpExtInOctets.
# TYPE node_netstat_IpExt_InOctets untyped
node_netstat_IpExt_InOctets 5.41694886709e+11
```

**Comment by jglapa** [comment]
Thanks @beorn7 for the detailed explanation .
Just wanted to follow up in this thread in case other people encountered issue alike.
All clear now!
