### ISSUE TITLE
 pushgateway  Reception problem

### ISSUE THREAD

**Issue by peixiaoqing** [prometheus/pushgateway#196]
Hello, developers.
Our pushgateway always receives messages and receives them every second, as shown in the figure, how do we handle this

![1534235736 1](https://user-images.githubusercontent.com/35130532/44081014-4765da5e-9fe0-11e8-9bda-1908bda3f7bc.jpg)

**Comment by peixiaoqing** [comment]
Pushgateway reported error in Prometheus panel   “server returned HTTP status 500 Internal Server Error”；
Report wrong in the background “are inconsistent, help and type of the latter will have priority. This is bad. Fix your pushed metrics!" source="diskmetricstore.go:108"”
As shown in the picture
![1534243291 1](https://user-images.githubusercontent.com/35130532/44087250-ce037326-9ff1-11e8-9522-f5239b34e6a0.jpg)

![1534243356 1](https://user-images.githubusercontent.com/35130532/44087275-e9b2511e-9ff1-11e8-8bbb-76d98fba186c.jpg)

**Comment by beorn7** [comment]
You have to read the whole error message. It's not pretty, admittedly, but this whole long string with angle brackets and escaped quotes is a string representation of the metric. (The weird formatting comes from the protobuf representation that was originally meant as the canonical data model and is still at the heart of the Go client library.)

What the error message tries to tell you is that the one pushed metric family `go_memstats_sys_bytes` has the HELP string `Number of bytes obtained by system. Sum of all system allocations.` while the other one has merely `Number of bytes obtained by system.` They are probably coming from different version of the Go client library. Handling those inconsistent HELP strings more gracefully is being tracked by #194, but in general, different HELP string for the same metric name cannot be represented by the Prometheus exposition format.

Work around 1: Update the pushing clients to use the same HELP string.

Work around 2: Check if you really want to push this metric. Usually, the Pushgateway should be used for only a handful of metrics. It looks like you are pushing the whole default registry. Perhaps (re-)read https://prometheus.io/docs/practices/pushing/ and look at the various ways of pushing documented [here](https://godoc.org/github.com/prometheus/client_golang/prometheus/push).

**Comment by beorn7** [comment]
As this is covered by #194 , I'll close this one.
