### ISSUE TITLE
add a parameter 

### ISSUE THREAD

**Issue by linuxcluster** [prometheus/pushgateway#201]
Can you add a parameter configuration that allows auto to delete pushgateway data immediately after the prometheus grabbing data.

**Comment by beorn7** [comment]
That would be in harsh contradiction with fundamental principles of Prometheus. The `/metrics` endpoint must be scrapeable at any time by anybody without changing the state of the exposing system (e.g. a human might inspect the endpoint, or you have an HA setup where multiple Prometheus servers scrape the same endpoints).
