### ISSUE TITLE
Cannot Scrape Push Gateway

### ISSUE THREAD

**Issue by peterj16** [prometheus/pushgateway#213]
I am running the latest version of pushgateway
wget against /metrics endpoint (http://localhost:9091/metrics from within the pushgateway container) returns http 500 without an error message.

I run the pushgateway based on the latest docker image, please find the extract from my comose file below:
prometheus_pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    command: ["--persistence.file=/data/persistence", "--web.listen-address=0.0.0.0:9091", "--web.telemetry-path=/metrics"]
    volumes:
      - ./prometheus_pushgateway/data:/data

wget against localhost:9091 without a path from within the pushgateway container returns the correct metrics as pushed from haproxy to the push gateway

**Comment by beorn7** [comment]
> wget against localhost:9091 without a path from within the pushgateway container returns the correct metrics as pushed from haproxy to the push gateway

That's weird. http://localhost:9091 should return a status page, but not metrics.

Could you double-check the PGW is correctly configured within your container? Which version are you running? Do things work normally with the same config but outside of a container?

**Comment by peterj16** [comment]
The file retrieved from localhost:9091 looks like this:
[index.zip](https://github.com/prometheus/pushgateway/files/2460593/index.zip)
I will try to attach the actual scrape results from haproxy as well. 
[extractfrompersistencefile.zip](https://github.com/prometheus/pushgateway/files/2460604/extractfrompersistencefile.zip)
To me the persistence file looks funny.

The corresponding section of the docker-compose file looks like this:
  prometheus_pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    command: ["--persistence.file=/data/persistence", "--web.listen-address=0.0.0.0:9091", "--web.telemetry-path=/metrics"]
    volumes:
      - ./prometheus_pushgateway/data:/data

I would assume that means we are using the latest docker image

**Comment by beorn7** [comment]
Your retrieved index.html is indeed the status page. This status page includes a rendering of the metrics, but is not the /metrics exposition itself.

However, from the metrics shown, it looks you are pushing whole metrics usually exposed by other systems i.e. you are trying to use the PGW to turn Prometheus into a push-based monitoring systems. That's doomed to fail. Please read https://prometheus.io/docs/practices/pushing/

My theory is that among the many metrics you have pushed, there might be an inconsistency (might be as minor as in the help string, which will be addressed by #194 ). In that case, you get a 500 response, but it _should_ have an error message. Perhaps your config is swallowing the message somehow.

In general, this doesn't look like a bug but more a problem with your usage pattern. It makes more sense to have discussions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your questions, and the whole community can benefit from the answers provided.

**Comment by beorn7** [comment]
And BTW: The persistence file uses a binary format. It is just expected to look "funny" in a text editor.

**Comment by peterj16** [comment]
I have tried removing all help texts (the lines starting with '#'). I removed the persistence file and restartet the container. Unfortunately this does not fix anything. 

As there are no error log statements and localhost:9091/metrics still returns 500 without a body, it might be relevant to your git project after all. I therefore attached the following information:
- Return from GET to /metrics endpoint
- Pushgateway log messages

I loosely followed this guide: https://zpjiang.me/2017/07/10/Push-based-monitoring-for-Prometheus/ , replacing the node exporter with the haproxy _exporter. 
I assume that, while this is not usage as designed, it might be one rather common use case (i.e. pulling metrics from an exporter and pushing to your gateway)
I hope this helps you in anyway. I will consider moving to graphite instead.

-----


Unfortunately there is no error log message:
wget localhost:9091/metrics
Connecting to localhost:9091 (127.0.0.1:9091)
wget: server returned error: HTTP/1.1 500 Internal Server Error

And from docker logs [container id]:
time="2018-10-11T06:34:01Z" level=info msg="Starting pushgateway (version=0.5.2, branch=HEAD, revision=231071b3e0a57b58df717bba5f4e5d88cac95389)" source="main.go:67"
time="2018-10-11T06:34:01Z" level=info msg="Build context (go=go1.10.3, user=root@c95e387ff56a, date=20180615-16:11:56)" source="main.go:68"
time="2018-10-11T06:34:01Z" level=info msg="Listening on 0.0.0.0:9091." source="main.go:124"
time="2018-10-11T06:39:02Z" level=info msg="Metrics persisted to '/data/persistence'." source="diskmetricstore.go:170"

**Comment by peterj16** [comment]
First of all after my research I feel that the title is inappropriate: I can push to the gateway but the scrape URL of pushgateway does not work with data scraped from haproxy 0.9 which is pushed to pushgateway. Do you mind if I rename this?

----

I have tried removing all help texts (the lines starting with '#'). I removed the persistence file and restartet the container. Unfortunately this does not fix anything. 

As there are no error log statements and localhost:9091/metrics still returns 500 without a body, it might be relevant to your git project after all. I therefore attached the following information:
- Return from GET to /metrics endpoint
- Pushgateway log messages

I loosely followed this guide: https://zpjiang.me/2017/07/10/Push-based-monitoring-for-Prometheus/ , replacing the node exporter with the haproxy _exporter. 
I assume that, while this is not usage as designed, it might be one rather common use case (i.e. pulling metrics from an exporter and pushing to your gateway)
I hope this helps you in anyway. I will consider moving to graphite instead.
Thank you for your quick responses. I really appreciate that!

-----


Unfortunately there is no error log message:
wget localhost:9091/metrics
Connecting to localhost:9091 (127.0.0.1:9091)
wget: server returned error: HTTP/1.1 500 Internal Server Error

And from docker logs [container id]:
time="2018-10-11T06:34:01Z" level=info msg="Starting pushgateway (version=0.5.2, branch=HEAD, revision=231071b3e0a57b58df717bba5f4e5d88cac95389)" source="main.go:67"
time="2018-10-11T06:34:01Z" level=info msg="Build context (go=go1.10.3, user=root@c95e387ff56a, date=20180615-16:11:56)" source="main.go:68"
time="2018-10-11T06:34:01Z" level=info msg="Listening on 0.0.0.0:9091." source="main.go:124"
time="2018-10-11T06:39:02Z" level=info msg="Metrics persisted to '/data/persistence'." source="diskmetricstore.go:170"

**Comment by beorn7** [comment]
https://zpjiang.me/2017/07/10/Push-based-monitoring-for-Prometheus/ is _precisely_ how not to use the Pushgateway.

If you try `curl` instead of `wget`, you should see an error message. `wget` doesn't display it for some reason.

**Comment by peterj16** [comment]
Hello Björn,
thank you for your help. I didn't know that wget did not return error message bodies. You were absolutely right the issue was related to your issue #194 . 
I removed the help lines and I removed KPIs not specific to haproxy:
# cut out all help texts
sed -i '/^#.*/d' ./metrics
# Remove all go metrics
sed -i '/^go.*/d' ./metrics
# Remove all process metrics
sed -i '/^process.*/d' ./metrics
# Remove all http request http response metrics
sed -i '/^http_re.*/d' ./metrics

This will work. I understand that this is not what you would want the tool to be used for. We use it for ephemeral containers and do not feel comforable either hosting prometheus closer to our loadbalancers or opening the ports.

**Comment by peterj16** [comment]
Hello Björn,
thank you for your help. I didn't know that wget did not return error message bodies. You were absolutely right the issue was related to your issue #194 . 
I removed the help lines and I removed KPIs not specific to haproxy:
# cut out all help texts
sed -i '/^#.*/d' ./metrics
# Remove all go metrics
sed -i '/^go.*/d' ./metrics
# Remove all process metrics
sed -i '/^process.*/d' ./metrics
# Remove all http request http response metrics
sed -i '/^http_re.*/d' ./metrics

This will work. I understand that this is not what you would want the tool to be used for. We use it for ephemeral containers and do not feel comforable either hosting prometheus closer to our loadbalancers or opening the ports.

**Comment by silasnatter** [comment]
Hey i have kind of the same problem.
I'm running a prometheus server and pushgateway using docker. I also wrote a script in python, which exports the metrics from a Windows client to the pushgateway. I can see the metrics at "http:SERVER-IP:9091/metrics" **but** on "http:SERVER-IP:9090/targets" the target "pushgateway" state is down. 
For more information, feel free to ask.
Appreciate any help. 
![chrome_4dB5EGKEd6](https://user-images.githubusercontent.com/61582769/99238116-a300a300-27f9-11eb-9128-afb844520d75.png)

**Comment by beorn7** [comment]
This doesn't seem like a bug in the Pushgateway. It appears you haven't set up the scrape properly. I recommend to use the community channels listed in https://prometheus.io/community/ to get help. In particular, the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) is a much better fit than commenting on a closed GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by silasnatter** [comment]
ok thank you, i will delete the post
