### ISSUE TITLE
Crashing pushgateway 0.6.0 when filepath not correct

### ISSUE THREAD

**Issue by praetp** [prometheus/pushgateway#223]
We upstepped from 0.4.0 to 0.6.0

and we get this crash

> 2018/11/27 12:01:26 http: panic serving 10.0.22.230:39122: runtime error: invalid memory address or nil pointer dereference
> goroutine 424 [running]:
> net/http.(*conn).serve.func1(0xc000070dc0)
>         /usr/local/go/src/net/http/server.go:1746 +0xd0
> panic(0x8d5dc0, 0xdc8cb0)
>         /usr/local/go/src/runtime/panic.go:513 +0x1b9
> github.com/prometheus/pushgateway/storage.copyMetricFamily(...)
>         /go/src/github.com/prometheus/pushgateway/storage/diskmetricstore.go:331
> github.com/prometheus/pushgateway/storage.(*DiskMetricStore).GetMetricFamilies(0xc00001d220, 0x0, 0x0, 0x0)
>         /go/src/github.com/prometheus/pushgateway/storage/diskmetricstore.go:118 +0x4e6
> main.main.func1(0x1, 0x0, 0x9328c0, 0xc00031ad38, 0xc0002fc1a0)
>         /go/src/github.com/prometheus/pushgateway/main.go:82 +0x2a
> github.com/prometheus/pushgateway/vendor/github.com/prometheus/client_golang/prometheus.GathererFunc.Gather(0xc000179cc0, 0x0, 0x0, 0x0, 0x1, 0xc00031ad38)
>         /go/src/github.com/prometheus/pushgateway/vendor/github.com/prometheus/client_golang/prometheus/registry.go:189 +0x27
> github.com/prometheus/pushgateway/vendor/github.com/prometheus/client_golang/prometheus.Gatherers.Gather(0xc000177ea0, 0x2, 0x2, 0xc0001862d0, 0x203000, 0x203000, 0x7fa7a72bcc90, 0x5)
>         /go/src/github.com/prometheus/pushgateway/vendor/github.com/prometheus/client_golang/prometheus/registry.go:671 +0xcca
> github.com/prometheus/pushgateway/vendor/github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x7fa7a504a258, 0xc0002cfd10, 0xc0000df200)
>         /go/src/github.com/prometheus/pushgateway/vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:116 +0x59
> net/http.HandlerFunc.ServeHTTP(0xc0001d6000, 0x7fa7a504a258, 0xc0002cfd10, 0xc0000df200)
>         /usr/local/go/src/net/http/server.go:1964 +0x44
> github.com/prometheus/pushgateway/vendor/github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7fa7a504a258, 0xc0002cfd10, 0xc0000df200)
>         /go/src/github.com/prometheus/pushgateway/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:40 +0xa9
> net/http.HandlerFunc.ServeHTTP(0xc0001d4270, 0x7fa7a504a258, 0xc0002cfd10, 0xc0000df200)
>         /usr/local/go/src/net/http/server.go:1964 +0x44
> github.com/prometheus/pushgateway/vendor/github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0xa24c20, 0xc0003ee540, 0xc0000df200)
>         /go/src/github.com/prometheus/pushgateway/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:100 +0xda
> net/http.HandlerFunc.ServeHTTP(0xc0001d4360, 0xa24c20, 0xc0003ee540, 0xc0000df200)
>         /usr/local/go/src/net/http/server.go:1964 +0x44
> github.com/prometheus/pushgateway/vendor/github.com/julienschmidt/httprouter.(*Router).Handler.func1(0xa24c20, 0xc0003ee540, 0xc0000df200, 0x0, 0x0, 0x0)
>         /go/src/github.com/prometheus/pushgateway/vendor/github.com/julienschmidt/httprouter/router.go:244 +0x4d
> github.com/prometheus/pushgateway/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00017dc40, 0xa24c20, 0xc0003ee540, 0xc0000df200)
>         /go/src/github.com/prometheus/pushgateway/vendor/github.com/julienschmidt/httprouter/router.go:344 +0x766
> net/http.serverHandler.ServeHTTP(0xc00017b520, 0xa24c20, 0xc0003ee540, 0xc0000df200)
>         /usr/local/go/src/net/http/server.go:2741 +0xab
> net/http.(*conn).serve(0xc000070dc0, 0xa25420, 0xc0003a7340)
>         /usr/local/go/src/net/http/server.go:1847 +0x646
> created by net/http.(*Server).Serve
>         /usr/local/go/src/net/http/server.go:2851 +0x2f5

Later we discovered our filepath had a double forward slash in it, so the file could not be read.
This was not clear from the above error at all.

**Comment by beorn7** [comment]
I don't think the double slash did this. The call stack above points to a metric family without metrics. This typically happens due to storage corruptions. The Pushgateway should definitely react more gracefully. I have created #228 for that. Please have a look.

**Comment by beorn7** [comment]
Only now I realize the impact of your first sentence: "We upstepped from 0.4.0 to 0.6.0". This cannot work, actually, and perfectly explains your observed behavior. I'll clarify the CHANGELOG.md.
