### ISSUE TITLE
Instance is not filled in with IP address if it's an IPv6 address

### ISSUE THREAD

**Issue by aecolley** [prometheus/pushgateway#23]
If the client address is an IP address, the `instance` field is supposed to default to it. However, this breaks when the client address is an IPv6 address (e.g. `[::1]:49126`), because the parsing code only looks for the first colon.

Suggested fix: https://github.com/prometheus/pushgateway/pull/22

**Comment by beorn7** [comment]
Thanks for the fix. Closing.
