### ISSUE TITLE
Add an endpoint and UI button to wipe the storage completely

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#264]
If too much garbage has been pushed, you might want to erase the whole storage and start from a clean slate. Currently, you would do the following:
- shut down the PGW
- delete the persistence file
- start PGW again

It would be easy to add an endpoint like `/-/reset` or `/-/wipe`, only active if a (yet to be added) flag ~~`--web.enable-lifecycle`~~ `--web.enable-admin-api` is set (similar to #136).

If that behavior is activated, it would also be good to add a button to the UI “Delete all groups”.

**Comment by brian-brazil** [comment]
This would be an admin endpoint rather than lifecycle. We should also have it as PUT rather than POST, for XSRF reasons.

**Comment by beorn7** [comment]
Ah right, the Prometheus server has `--web.enable-admin-api`, should be the same here.

**Comment by snebel29** [comment]
I would like to work on this feature, I will take a look to the code and comment back

**Comment by snebel29** [comment]
This is the current TODO list for this feature request

- [x] Add API call to wipe the storage completely
- [ ] Document `/wipe` API call
- [ ] Add button to delete all metric groups

**Comment by beorn7** [comment]
This is done. I'll cut a release at my next convenience so that the general public can make use of it.
\o/
