### ISSUE TITLE
Deal with clash between pushgateway's own metrics and pushed metrics

### ISSUE THREAD

**Issue by mwitkow-io** [prometheus/pushgateway#27]
After upgrading our Java client libraries to `0.0.8`, we started getting problems with Prometheus scraping the `/metrics` page of PushGateway.

```
An error has occurred:

metric family with duplicate name injected: name:"process_start_time_seconds" help:"Start time of the process, in unixtime." type:GAUGE metric:<label:<name:"job" value:"internal-Gianni-PW-RHODRIK1" > label:<name:"instance" value:"PW-RHODRIK1" > gauge:<value:1.424863714816e+09 > > metric:<label:<name:"job" value:"internal-michal-wintermute" > label:<name:"instance" value:"wintermute" > gauge:<value:1.424803036927e+09 > > metric:<label:<name:"job" value:"internal-chris-PW-RENDER1-PC" > label:<name:"instance" value:"PW-RENDER1-PC" > gauge:<value:1.424863870177e+09 > > metric:<label:<name:"job" value:"internal-callum-PW-CALLUML1" > label:<name:"instance" value:"PW-CALLUML1" > gauge:<value:1.424864927792e+09 > > metric:<label:<name:"job" value:"internal-Virgil-VirgilNotebook" > label:<name:"instance" value:"VirgilNotebook" > gauge:<value:1.424865024272e+09 > > metric:<label:<name:"job" value:"internal-rok-dev-fcaa141b9c88" > label:<name:"instance" value:"dev-fcaa141b9c88" > gauge:<value:1.424861518748e+09 > > 
```

Eyeballing the main page of PushGateway, everything is fine, the data has values and each `job`-`instance` pair has a single value. The error is fairly cryptic :(

Any idea how to debug this further?

**Comment by brian-brazil** [comment]
I'm going to guess the process_start_time_seconds from the pushgateway itself is clashing with what's been pushed to the pushgateway.

May I ask why you're pushing process_start_time_seconds to the pushgateway? For batch jobs you generally want a separate registry with very specific metrics pushed, which don't typically include the standard exports or jvm stats.

**Comment by mwitkow-io** [comment]
Unfortunately we need to use the pushgateway for some use cases. In this case we need monitoring attached to processes running on developer desktops.

**Comment by beorn7** [comment]
I'm considering adding a flag to disable pushgateway's own metrics to avoid that clash. But as Brian said, this is not a typical use case...

**Comment by brian-brazil** [comment]
You'd still want to be able to check the performance of the push gateway itself, so I'd say long term we should be looking at gracefully handing this situation by merging in the metrics.

**Comment by mwitkow-io** [comment]
we would really appreciate a quick short term fix for this.

as for merging, is it necessary? wouldn't it be more elegant to separate out PushGateway's own metrics in `/metrics` and the data it gets from other endpoints in `/pushed_metrics`?

**Comment by brian-brazil** [comment]
The problem with two endpoints is you then need to scrape both of them, which can makes things a bit more difficult manage.

There's a general discussion to be had around how we pull in metrics and labels from things like the push gateway that provide labels that are usually target labels.

**Comment by beorn7** [comment]
Gracefully handling the current situation with minimal change would require the https://github.com/prometheus/client_golang/blob/master/prometheus/registry.go#L169 method to do more checking and merge metric families with existing ones. I'll look into that...

**Comment by mwitkow-io** [comment]
We've put a temporary work around by hacked the Java client to have a prefix for its metrics. Bjoern, I see you've took this up, is there a PushGateway-side fix in the works? :)

**Comment by beorn7** [comment]
Yes, but I cannot give you an ETA.

**Comment by mwitkow-io** [comment]
Knowing you're on it is more than enough :) Thanks!

**Comment by bketelsen** [comment]
+1 - got bitten by this today.  Created a command in Go to do some batch processing.  Used the go prometheus library, registered one CounterVec, and get this error in the PushGateway.  I don't see anywhere to disable my client pushing these "extra" metrics.  Am I missing something?

**Comment by beorn7** [comment]
@bketelsen You are right, if you use the standard client_golang setup, you already run into this issue. That's certainly not intended. The easy way should always work. I'll try to fix this by the end of the week.

**Comment by beorn7** [comment]
@bketelsen @mwitkow-io So now you have two ways of solving the problem:

1. Build pushgateway from head with the head version of `client_golang` (it's not yet vendored in the pushgateway, so just do `make clean && make` or `go get -u`).
2. Use the new convenience functions `PushCollectors` and `PushAddCollectors` in `client_golang` (HEAD).

**Comment by bketelsen** [comment]
Thank you!!

**Comment by mwitkow-io** [comment]
Fantastic! Danke shoen!
