### ISSUE TITLE
Disk out of space

### ISSUE THREAD

**Issue by paprickar** [prometheus/pushgateway#277]
## Feature request
**Use case. Why is this important?**
Running prometheus-pushgateway with persistent disks for a longer time will cause a full disk. I would like to request a feature to overwrite the oldest data when the maximum disk size is used

**Comment by beorn7** [comment]
This would result in the uncontrolled loss of older metrics after a restart.

Effectively, it would implement a fuzzy version of the metric timeout or TTL that was decided to be a non-goal for the Pushgateway. See https://github.com/prometheus/pushgateway#non-goals .

In different news: If you push so many metrics to the Pushgateway that you can fill your disk, you are probably not using the Pushgateway for what it was meant to be used for. See https://prometheus.io/docs/practices/pushing/ .

If you want to continue with your  usage pattern, you have to create a clean-up mechanism (via the DELETE HTTP call) yourself. Sorry for that.

**Comment by paprickar** [comment]
Alright thanks for the explanation
