### ISSUE TITLE
failed to pull and unpack image "docker.io/prom/pushgateway:v0.9.1"

### ISSUE THREAD

**Issue by r0bj** [prometheus/pushgateway#278]
## Bug Report
**What did you do?**

```
# crictl pull prom/pushgateway:v0.9.1
FATA[0000] pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/prom/pushgateway:v0.9.1": failed to unpack image on snapshotter overlayfs: content digest sha256:7351147077496a942c478cb3f4c850c1feb5c96a614472582c3feae07de959db: not found
```

**What did you expect to see?**

Image is pulled from registry.
Similar to what can be seen during pulling older image:
```
# crictl pull prom/pushgateway:v0.7.0
Image is up to date for sha256:843b4317ed070d82309dc8db8d5fadeb1b84faa4f04bffb06cac7f2373321bfd
```

**What did you see instead? Under which circumstances?**

```
# crictl pull prom/pushgateway:v0.9.1
FATA[0000] pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/prom/pushgateway:v0.9.1": failed to unpack image on snapshotter overlayfs: content digest sha256:7351147077496a942c478cb3f4c850c1feb5c96a614472582c3feae07de959db: not found
```

**Environment**
crictl v1.13.0
containerd 1.2.5

**Comment by beorn7** [comment]
Is this still ongoing? I'm not using `crictl`, but I can use `docker pull` without issues.

**Comment by r0bj** [comment]
@beorn7 yes, it's still ongoing.

**Comment by beorn7** [comment]
Weird. If anybody who knows `crictcl` could share insight what might be going in here, it would be much appreciated.

**Comment by r0bj** [comment]
I believe this have been fixed in HEAD https://github.com/containerd/containerd/commit/1161409779f0275f5e65a697d587ff893f9f9188 and cherry-picked in https://github.com/containerd/containerd/pull/3512

**Comment by beorn7** [comment]
Good to hear. Thanks.
