### ISSUE TITLE
not able to run prom/pushgateway docker image with port 80

### ISSUE THREAD

**Issue by sandlis** [prometheus/pushgateway#280]
## Bug Report
**What did you do?**
`docker run prom/pushgateway:v0.9.1 --web.listen-address :80`

**What did you expect to see?**
We should be able to run pushgateway with port 80

**What did you see instead? Under which circumstances?**
I saw an error `docker run prom/pushgateway:v0.9.1 --web.listen-address :80`

**Environment**

* Pushgateway version:

		version=0.9.1

* Pushgateway command line:

		Insert full command line.

* Logs:
```
level=info ts=2019-08-06T13:56:18.696Z caller=main.go:79 msg="starting pushgateway" version="(version=0.9.1, branch=HEAD, revision=b4410a3a361a770a084007ef50aebf42d0e8793c)"
level=info ts=2019-08-06T13:56:18.696Z caller=main.go:80 build_context="(go=go1.12.7, user=root@556a5d403380, date=20190801-14:03:20)"
level=info ts=2019-08-06T13:56:18.697Z caller=main.go:133 listen_address=:80
level=error ts=2019-08-06T13:56:18.697Z caller=main.go:136 err="listen tcp :80: bind: permission denied"
```

**Comment by hairyhenderson** [comment]
@sandlis the prom/pushgateway Docker image runs as non-root, which means that it can not listen to port 80 (or any port below 1024).

However, there's not really a reason you should need to change the listening port inside the container - what you're probably looking for instead is the `-p`/`--publish` argument to `docker run` to map a host port to an inside container port:

```
docker run -p 80:9091 prom/pushgateway:v0.9.1
```

**Comment by beorn7** [comment]
@sandlis does that fix your issue?

**Comment by sandlis** [comment]
Sounds good to me. Closing this. Thanks!
