### ISSUE TITLE
Vendor all depencies and refactor Makefile...

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#29]
... so it matches the way it is done in other Prometheus projects.

**Comment by grobie** [comment]
Could have prevented #35.

**Comment by beorn7** [comment]
https://github.com/prometheus/pushgateway/pull/40 switches to `Makefile.COMMON`. I'll postpone the vendoring until we have clarity which direction to go (godep? gb? something completely different?).

**Comment by grobie** [comment]
@beorn7 Any conclusion here already? GOVENDOREXPERIMENT (+ godep)?

**Comment by beorn7** [comment]
Same as in prometheus/prometheus: GOVENDOREXPERIMENT, and use the dependency management tool of your choice as long as it creates what is compatible with GOVENDOREXPERIMENT.

**Comment by beorn7** [comment]
Fixed thanks to @sdurrheimer
