### ISSUE TITLE
--web.enable-admin-api doesn't exist.

### ISSUE THREAD

**Issue by pymag09** [prometheus/pushgateway#294]
## Bug Report
**What did you do?**
I tried to use option --web.enable-admin-api
**What did you expect to see?**
I expect it to work
**What did you see instead? Under which circumstances?**
pushgateway: error: unknown long flag '--web.enable-admin-api', try --help
**Environment**
Linux
* System information:
Linux 5.0.0-29-generic x86_64
* Pushgateway version:
0.9.1
* Pushgateway command line:
docker run -it prom/pushgateway --web.enable-admin-api
* Logs:
```
Status: Downloaded newer image for prom/pushgateway:latest
pushgateway: error: unknown long flag '--web.enable-admin-api', try --help

```

**Comment by beorn7** [comment]
I will actually release v0.10 today. (Which will be _almost_ a release candidate for v1.0.)
