### ISSUE TITLE
why does docker latest compose high size increase

### ISSUE THREAD

**Issue by ssulleyymmann** [prometheus/pushgateway#296]
why does docker latest compose high size increase? 0.3.0 version have not problem. 
how should configuration?  

size log => 

root@:/var/lib/docker/containers# du -h --max-depth=1
48K     ./30823482693dacfd28619254fd02ef291d20c0dc453b0e195a5665175369aa92
48K     ./7d9e697f3d96357b04c5bb6ec1189e35a6521cafd966029430ff52fd388c49e0
**292K**    ./**98281cdf893b3882b415dfd31e1d0b09f91dc5f108aef31bf33c04614f88d843**
392K    .
root@:/var/lib/docker/containers# du -h --max-depth=1
48K     ./30823482693dacfd28619254fd02ef291d20c0dc453b0e195a5665175369aa92
48K     ./7d9e697f3d96357b04c5bb6ec1189e35a6521cafd966029430ff52fd388c49e0
**540K**    ./**98281cdf893b3882b415dfd31e1d0b09f91dc5f108aef31bf33c04614f88d843**
640K    .
root@/var/lib/docker/containers# du -h --max-depth=1
48K     ./30823482693dacfd28619254fd02ef291d20c0dc453b0e195a5665175369aa92
48K     ./7d9e697f3d96357b04c5bb6ec1189e35a6521cafd966029430ff52fd388c49e0
**1.1M**    ./**98281cdf893b3882b415dfd31e1d0b09f91dc5f108aef31bf33c04614f88d843**
1.2M    .
root@:/var/lib/docker/containers# docker container ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                    NAMES
30823482693d        grafana/grafana     "/run.sh"                58 seconds ago       Up 57 seconds       0.0.0.0:3000->3000/tcp   grafana
7d9e697f3d96        prom/prometheus     "/bin/prometheus --c…"   About a minute ago   Up About a minute   0.0.0.0:9090->9090/tcp   prometheus
**98281cdf893b**        prom/pushgateway    "/bin/pushgateway --…"   About a minute ago   Up About a minute   0.0.0.0:9091->9091/tcp   pushgateway

docker compose service => 
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    command: ["--persistence.file=/data/persistence", "--web.listen-address=0.0.0.0:9091", "--web.telemetry-path=/metrics"]
    volumes:
      - /prometheus_data/pushgateway:/data
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:   
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

**Comment by snebel29** [comment]
Hi @ssulleyymmann,
It'd be great if you can provide the precise steps and configurations that you are following (including data being pushed if any) to easily reproduce this case.

Have you tried something like (non tested)
```
$ cd /var/lib/docker/containers/98281cdf893b3882b415dfd31e1d0b09f91dc5f108aef31bf33c04614f88d843
$ find . -type f -printf '%T@ %s %p\n' | sort -n | tail -n 25
```
in trying to find new files and/or files growing within the container instance?

Thanks

**Comment by ssulleyymmann** [comment]
hi, @snebel29,
thank you for feedback.. 
I can see in container detail, but I don't know solution, can I close log? 
root@:/var/lib/docker/containers/98281cdf893b3882b415dfd31e1d0b09f91dc5f108aef31bf33c04614f88d843# find . -type f -printf '%T@ %s %p\n' | sort -n | tail -n 25
1571119753.4232651040 174 ./hosts
1571119753.4232651040 71 ./resolv.conf.hash
1571119753.4392651820 13 ./hostname
1571119753.5992659660 58 ./resolv.conf
1571119753.9912678850 1582 ./hostconfig.json
1571119753.9912678850 3700 ./config.v2.json
1571136170.7932626190 **422366843** ./98281cdf893b3882b415dfd31e1d0b09f91dc5f108aef31bf33c04614f88d843-**json**.log
root@:/var/lib/docker/containers/98281cdf893b3882b415dfd31e1d0b09f91dc5f108aef31bf33c04614f88d843# find . -type f -printf '%T@ %s %p\n' | sort -n | tail -n 25
1571119753.4232651040 174 ./hosts
1571119753.4232651040 71 ./resolv.conf.hash
1571119753.4392651820 13 ./hostname
1571119753.5992659660 58 ./resolv.conf
1571119753.9912678850 1582 ./hostconfig.json
1571119753.9912678850 3700 ./config.v2.json
1571136200.7933537390 **423136698** ./98281cdf893b3882b415dfd31e1d0b09f91dc5f108aef31bf33c04614f88d843-**json**.log
root@ip-10-20-60-44:/var/lib/docker/containers/98281cdf893b3882b415dfd31e1d0b09f91dc5f108aef31bf33c04614f88d843#

**Comment by beorn7** [comment]
Is the conclusion here that the log file is growing a lot?
What's the content of your log file? It might spit out a lot of errors if you are really upgrading from v0.3. The on-disk format has changed multiple times, and you need to upgrade in stages if you want to keep your persistence file. See CHANGELOG.md. But that's just a wild guess.

For a production setup, you should have some kind of log rotation set up. Otherwise, your log files will always fill your storage eventually.

**Comment by snebel29** [comment]
That's just docker's log file for the specific container and it's normal to have one growing if the application is doing some logging, unless there is something abnormal with the way Pushgateway is logging this is nothing to worry about.

> For a production setup, you should have some kind of log rotation set up. Otherwise, your log files will always fill your storage eventually.

Definitively recommended, I think last versions of docker ships with features to keep logs under control, and compose expose some of them, take a look to [specify max log json file size in docker compose](https://stackoverflow.com/questions/39078715/specify-max-log-json-file-size-in-docker-compose)

I hope that helps.

**Comment by ssulleyymmann** [comment]
@beorn7, yes, log file is growing a lot,  thanks for your suggestion.
@snebel29, I fixed docker log size and problem solved :) thank you so much..
