### ISSUE TITLE
Push response code change should be called out as Breaking

### ISSUE THREAD

**Issue by kfdm** [prometheus/pushgateway#301]
I'm not sure how the wording should be handled (hence not submitting a PR yet) but the response code change in #290 is a fairly breaking change for [client_java] and should probably be called out more even though it is fixed [upstream]. I think client_python is ok
~Looks like [client_golang] may be affected the same way~ my mistake on client_golang. I was looking at the wrong method. It looks like it's probably fine

[client_java]: https://github.com/prometheus/client_java
[upstream]: https://github.com/prometheus/client_java/pull/507
[client_golang]: https://github.com/prometheus/client_golang/blob/e0e84de03633bfe7131293cf1d86cb018220b98b/prometheus/push/push.go#L223-L227

**Comment by beorn7** [comment]
Breaking changes are marked as `[CHANGE]` in the CHANGELOG.md. See https://github.com/prometheus/pushgateway/releases/tag/v0.10.0 where the status code change is clearly called out.

I would have mentioned it explicitly again in my hand-written announcement mail if I had anticipated that it is a problem for some of the client libraries. But in the plain CHANGELOG.md, `[CHANGE]` is the marker for breaking changes. (Non-breaking changes would be marked as feature or enhancement.)
