### ISSUE TITLE
Pushgateway metrics disappearing periodically without PUT

### ISSUE THREAD

**Issue by Leulz** [prometheus/pushgateway#305]
## Bug Report
**What did you do?**
I am checking metrics that are pushed on the Pushgateway.

**What did you expect to see?**
Continuous metrics, like so:
![Screenshot from 2019-10-19 14-02-41](https://user-images.githubusercontent.com/6234045/67148742-3115fd00-f279-11e9-92c1-bdbf25c6ec25.png)

**What did you see instead? Under which circumstances?**
Most of the data started to have gaps, like so:
![Screenshot from 2019-10-19 14-04-28](https://user-images.githubusercontent.com/6234045/67148755-67537c80-f279-11e9-95fa-68e2e64bd71e.png)

When sending a request via curl to the `/metrics` endpoint of the Pushgateway, and counting the lines that have the `{metric_name}`, I noticed that sometimes it suddenly goes down a bunch (to like 8), and then it goes back to a large value (464).

I have already verified, by querying the `pushgateway_http_requests_total` metric, that the Pushgateway is only receiving `POST` and `GET` requests, never `PUT`. So I do not understand how these gaps are appearing, since my understanding is that metrics should never disappear from Pushgateway if I'm always sending data via `POST`.

So, apparently something is deleting the data sporadically.

It should be noted that this behavior only happens with metrics pushed by a specific job. Most metrics from other jobs that push onto the Pushgateway do not seem to have gaps.

Also, something that might be related is that the `container_cpu_cfs_throttled_seconds_total` metric for the Pushgateway reports very large values. I am not sure if that is related, but I think it's something that I should mention. Below is the graph for that metric for the last 24 hours.
![Screenshot from 2019-10-19 14-32-48](https://user-images.githubusercontent.com/6234045/67149080-5e64aa00-f27d-11e9-988e-097331d3a7a7.png)

UPDATE: I have increased the CPU, the throttling is pretty much not happening anymore, but the problem persists. :disappointed: 

**Environment**

* System information:

`Linux 4.9.0-6-amd64 x86_64`

* Pushgateway version:

```
pushgateway, version 0.8.0 (branch: HEAD, revision: d90bf3239c5ca08d72ccc9e2e2ff3a62b99a122e)
  build user:       root@00855c3ed64f
  build date:       20190413-11:29:19
  go version:       go1.11.8
```

* Pushgateway command line:

`/bin/pushgateway`

* Logs:
Currently the log level is info, and I have not found anything relevant in the logs.

@beorn7

**Comment by beorn7** [comment]
The gaps in your graph look pretty long. Is their length in agreement with the times where you see metrics going away on the Pushgateway? Are you graphing just that metric or some more complex expression?

In very general, a `POST` request replaces all metrics with the same name (in the group you push to) with the metrics you push. The difference to `PUT` is that the latter replaces all metrics in the group by the metrics pushed.

For simplicity, let's assume you have only one group you push to. If that group has 464 metrics named `foo` (with different labels each) and 42 metrics named `bar` and then you `POST` a set of 8 metrics named `foo` to the group, than the 464 `foo` metrics are replaced by the 8 `foo` metrics while the 42 `bar` metrics are kept.

The only way of pushing separately a metric without replacing metrics with the same name is to push them into separate groups.

**Comment by Leulz** [comment]
I see. I understood the difference between using POST or PUT wrongly. 

Then it's most likely an issue with the service that's sending this metric to Pushgateway, not with Pushgateway itself. 

I'm closing this issue, thank you very much!

**Comment by silvermissile** [comment]
this issue happens in my word too.   https://stackoverflow.com/questions/67668655/promethus-can-not-get-metrics-everytime-resultting-gaps-when-displaying-metrics
