### ISSUE TITLE
relax HELP / TYPE consistency checks

### ISSUE THREAD

**Issue by belm0** [prometheus/pushgateway#311]
To save metrics bandwidth from client nodes, we attempted to remove HELP and TYPE comments from the data sent to pushgateway.

However since it wouldn't be feasible to deploy this pruning instantly to the entire fleet of nodes, it resulted in e.g. "Metric families have inconsistent help strings" error.

Maybe I'll just be told "don't do that".   Please correct me if I'm wrong, but wouldn't there be a similar problem if I tried to fix a typo in the help description of a metric?  The fixed help string would be deployed to some machines first, inducing this pushgateway error.

Thanks for your patience if I'm misunderstanding.

**Comment by belm0** [comment]
Looking at README, I see this is only info level logging.

However in some uses deployment of help string changes to all nodes could take months, or we could indefinitely have a mismatch if customers don't upgrade the application.  (Maybe it's not normal for data from distribute nodes to come through a pushgateway, but here we are.)   It large amount of logging... could each unique message only be emitted once?

https://github.com/prometheus/pushgateway#about-metric-inconsistencies

**Comment by belm0** [comment]
I think for our use I'd prefer just an option to disable this logging.

It's an extreme amount logging given that the output includes the entire pushed metrics text, multiplied by the push rate...

**Comment by belm0** [comment]
summary:

  • proposing command-line option to disable HELP inconsistency warning - it's info level logging only, and deployments may not be able to avoid the inconsistencies (e.g. customer devices having old client code indefinitely).  Happy to make a PR if this is not controversial.
  • would be nice to have an option to relax or disable TYPE check, e.g. for our case where we want to migrate everything to `untyped`

I'm aware our use case may be considered in a gray area for pushgateway.

**Comment by belm0** [comment]
I'm caught up on the metrics TTL thread, so I can guess were this request is going.

If there is one useful suggestion I can contribute anyway, it would be to place this statement from that thread into the README, so that the position of the maintainers is clear:

> We actively discourage users from using the Pushgateway to turn Prometheus into a push-based monitoring system.

**Comment by beorn7** [comment]
- WRT `TYPE`: It's plainly impossible to create a valid exposition with different `TYPE`s for the same metric name. Thus, if PGW tolerated incompatible types, it would need to make a decision what type to change, and that decision simply cannot be made in a general way.
- WRT `HELP`: The same is in principle true for the help string. However, the help string doesn't usually come with implications as strong as the type, while at the same time, the differences are often minimal. (Or in other words, a type in the help string is common. A typo in `TYPE` is impossible.) Thus, we decided to tolerate inconsistent help strings, but it is still important enough to do it silently. Thus, the info logging. It would be weird to add config options to subdue individual kind of logs, and ever more so if the usage pattern _is_ in fact problematic. You could decrease the log level, or you have to use the features of your logging system to control what logs to see or save.
- WRT stating the most important non-goal in the README: You are actually right. It was probably too obvious to put it there. I have fixed that in #312. Please have a look.

**Comment by belm0** [comment]
I could see a rule "if pushed metric doesn't have a HELP or TYPE, use HELP or TYPE already seen" but it's rather niche to my original use case of trying to migrate towards omitting these from the data.
