### ISSUE TITLE
Introduce flag to disable push checks

### ISSUE THREAD

**Issue by benamazing** [prometheus/pushgateway#313]
Hi, 

We use pushgateway to collect app metrics. We used version 0.7 pushgateway before, and it worked well. Today we upgraded to v1.0, found the push performance decreased a lot, the avg push duration increased from less than 1 seconds to 300+ seconds. Is this a bug or any logic changed in pushgateway version > v0.7.0 ?

![image](https://user-images.githubusercontent.com/7868153/71170607-a2345980-2296-11ea-8383-e534232caf0a.png)

**Comment by beorn7** [comment]
This might very well be the check of pushed metrics introduced in [v0.10](https://github.com/prometheus/pushgateway/releases/tag/v0.10.0). May I ask how many metrics live on your Pushgateway? How long does it usually take to _scrape_ your Pushgateway? (The check was introduced with the rationale that pushes, with the check, will not take longer than scrapes, and that in sane setups, pushes are less frequent than scrapes.)

**Comment by benamazing** [comment]
> This might very well be the check of pushed metrics introduced in [v0.10](https://github.com/prometheus/pushgateway/releases/tag/v0.10.0). May I ask how many metrics live on your Pushgateway? How long does it usually take to _scrape_ your Pushgateway? (The check was introduced with the rationale that pushes, with the check, will not take longer than scrapes, and that in sane setups, pushes are less frequent than scrapes.)

We have aound 100 clients push the metrics to the same pushgateway. Each clients would push around 15,000 metrics with the interval of 60 seconds.

And prometheus scrapes pushgateway every 60 seconds as well. Each scrape cost around 6-8 seconds.

**Comment by beorn7** [comment]
Wow, that's wild… and indeed nothing the PGW was ever designed for.

6–8 seconds scrape is long but probably borderline OK. Same is true for the duration of a push. However, I can imagine what is happening here: With 100 clients each pushing every 60s, you have a push every 600ms. If the first push takes as long as a scrape, there will be more than 10 pushes coming in while it is still ongoing. Or in other words: Many pushes will overlap, slowing down each individual push, making even more pushes overlap. Death spiral ensues…

And yes, you push _way_ more frequently than you scrape.

With the load and usage pattern you have, it looks you are using the PGW to turn Prometheus into a push-based monitoring system. That's an explicit anti-goal of the PGW. I don't think the PGW should be optimized to cater for those use-cases. But perhaps we should consider a protection against too many concurrent pushes and reject further pushes if too many are still ongoing.

That wouldn't help in your situation. It would just make the problem more obvious (by replacing very long pushes with failed pushes). Recommendations for your case:
- Please don't use the PGW to turn Prometheus into a push-based monitoring system.
- If you really want to push from that many clients with that many metrics, you have to push less often (more like every 10 minutes or so).
- If you depend on the high push frequency, you could shard the PGW: Set up 10 instances and let 10 clients push to each.

**Comment by belm0** [comment]
just hit the same problem upgrading from 0.8 to 1.0.   CPU use appear to be increase well over 5x (hit container CPU limit and I haven't tried lifting it yet), and ready reports "write queue is full".

yes, we are using pushgateway contrary to what's intended.  We have a roadmap to migrate to pushprox, but in the meantime we wanted the improved error reporting in 1.0 (e.g. 0.8 only reports scrape errors in HTTP 500 error body)

**Comment by beorn7** [comment]
While I cannot really recommend the described use cases, it should be fairly easy to introduce a flag to switch off the correctness test for pushes. I was considering it anyway, but was hoping it wouldn't be necessary.

**Comment by beorn7** [comment]
Flag is in master. You can build from there to try it out. I'll also do a release soon.

**Comment by Feder1co5oave** [comment]
Does this issue manifest with a spike in the number of goroutines? It happens to us in a seemingly random fashion. The number of goroutines increases dramatically (see graph), the memory usage increases to ~200Mb and `/-/healthy` and `/-/ready` return 500, then the container gets killed by the kubelet.
We're using version v1.0.0. I've now updated to v1.1.0 and enabled `push.disable-consistency-check`

![image](https://user-images.githubusercontent.com/1869444/74860500-0c29b780-5349-11ea-9efa-71da3b80c1b4.png)

**Comment by beorn7** [comment]
If you push often enough so that the pushes overlap, you can certainly end up in a death spiral that leads to many goroutines and a lot of RAM usage.

**Comment by Feder1co5oave** [comment]
I honestly don't have that much control over when metrics get pushed, but
no particularly concurrent pushes come to my mind. I'd have to further
investigate into the pg metrics to find out.

**Comment by Feder1co5oave** [comment]
The rate of push requests increased from 5 to 6 - 10:
![image](https://user-images.githubusercontent.com/1869444/74876590-3f2d7480-5364-11ea-9242-7ab0b412ee6c.png)

The data rate did **not** increase. Does this seem wild to you?
![image](https://user-images.githubusercontent.com/1869444/74876767-903d6880-5364-11ea-8983-563c8f0d632f.png)

**Comment by beorn7** [comment]
If you push multiple times per second, you are certainly prone to get overlapping pushes.
It's arguably an abusive use of the PGW, but if you want to enable it, you can set the flag to disable push checks to make pushes fast.

I don't quite get what your problem is otherwise. Do you still see goroutine explosions when you have set the flag?

**Comment by Feder1co5oave** [comment]
No problem as of yet, but it had manifested very few times and I don't know
how to reproduce it. Fact is, whenever it dies, multiple grafana alerts are
triggered, so it is definitely a nuisance. I'd like to enable registry file
persistence too.
BTW we push metrics from Spark executors, and I wouldn't dare call
"multiple pushes" an abuse of a microservice.

Maybe the issue is the total number of metrics it holds. A complete scrape
returns around 4Mb of text. I'll see if I can prune some unused ones.

**Comment by beorn7** [comment]
If there is no doubt then that the flag is doing what it says on the tin, and it's more about how to run the PGW in a way that it doesn't fall over, I recommend to have the discussion on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a closed GitHub issue.

**Comment by Feder1co5oave** [comment]
You're right, this feels out of topic. I originally intended to write on #321 to find out if I was experiencing the same behavior or if it was something else. I eventually wrote here because that was marked as duplicate.

**Comment by vi4vikas** [comment]
I am deploying PGW v1.5.1 using the [helm chart v2.2.0](https://github.com/prometheus-community/helm-charts/tree/prometheus-pushgateway-2.2.0/charts/prometheus-pushgateway). I can see the flag set up to be false but as I put 
```
  extraArgs:
   - --push.disable-consistency-check=true
```
in my value.yaml file, the pod breaks as it fails to create the container. But with other flags like:
```
   - --persistence.file=/data/pushgateway.data
   - --persistence.interval=10m
```
it shows no issues. 

Any help on this?

**Comment by beorn7** [comment]
`--push.disable-consistency-check=true` doesn't work, you need `--no-push.disable-consistency-check`.

(In different news, asking question on a closed GH issue needs a lot of luck to give you an answer. Check out https://prometheus.io/community/ for better community support channels.)

**Comment by vi4vikas** [comment]
> `--push.disable-consistency-check=true` doesn't work, you need `--no-push.disable-consistency-check`.
> 
> (In different news, asking question on a closed GH issue needs a lot of luck to give you an answer. Check out https://prometheus.io/community/ for better community support channels.)

Thanks for the quick response, I tried 
```
  extraArgs:
   - --no-push.disable-consistency-check
```
Well the pod did go to running state and container is good and healthy but I can still see the flag set to false in PGW's UI

**Comment by alisonatwork** [comment]
It makes sense that `--no.push.disable-consistency-check` would result in a false setting, because according to the Kingpin docs, boolean flags use the `--no-` prefix to turn them off: https://github.com/alecthomas/kingpin?tab=readme-ov-file#boolean-values

It seems that you should never need to use `--no.push.disable-consistency-check` because the default state already is false, so setting `--push.disable-consistency-check` would do what we want, which is disable the costly checks.

Setting this for us shows a significant reduction in CPU usage for case of handling 10-20 pushes per second.
