### ISSUE TITLE
Update docker hub :latest tag with multiarch images

### ISSUE THREAD

**Issue by tdorsey** [prometheus/pushgateway#315]
## Bug Report

Installed the loki-stack helm chart, which uses the prometheus pushgateway internally

**What did you expect to see?**
A running pushgateway pod

**What did you see instead? Under which circumstances?**
`standard_init_linux.go:211: exec user process caused "exec format error"`
Inspecting the images pushed to docker.io, the latest tag shows:

ebca495ba277 | linux/amd64
0ca17ada3da1 | linux/amd64
6076d1a9d95d | linux/amd64

The master tag appears to have the correct architectures:

53cf78d1561c | linux/amd64
7ed3ae17c0d3 | linux/arm
6b016ef2c4ab | linux/arm64

**Environment**

* System information:

	Linux 4.9.196-63 aarch64

* Pushgateway version:

 image prom/pushgateway:v0.8.0
* Pushgateway command line:

n/a

* Logs:
```
n/a
```

**Comment by beorn7** [comment]
This is related to the discussion in #307.

It should be fixed in v1.0.1 (which is being cut right now). However, you actually have to use that version then. Older container images are unfortunately broken for non-amd64.

**Comment by beorn7** [comment]
v1.0.1 is pushed to both Docker Hub and Quay. After upgrading to v1.0.1, things should work as expected. Please follow up here if you still see issues.
