### ISSUE TITLE
Add arbitrary grouping.

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#32]
As discussed in https://github.com/prometheus/pushgateway/issues/18 , arbitrary grouping should be possible.

The `job` label will always be part of the group identifier. Any other labels can be added to it. All metrics pushed as part of a group will get the grouping labels forcefully set.

To push with arbitrary grouping, the REST API needs an extension to something like:

    /metric/jobs/some_job/groupby/{instance="foo",shard="bar"}

The old form `/metric/jobs/some_job/instances/some_instance` is just a special case of the above.

The DELETE semantics will change as it will always affect one whole group. There is no hierarchy anymore, every group is top level, no matter by what labels it is defined. The UI will be changed accordingly.

**Comment by brian-brazil** [comment]
How about `/metric/jobs/some_job/instance/foo/shard/bar`?

Escaping on the double quotes will throw many people off, especially in shell.

**Comment by beorn7** [comment]
That's a good point. But on the other hand, all label names have to remain unchanged then, just `jobs` is pluralized... (on yet another hand, `job` _is_ special as it _must_ be included...) To keep compatibility, we also had to coerce `instances` into `instance` (so you could never use `instances` as a label name - not that that would be a good idea, but it's still weird).

The pluralization of REST was always a bit weird in this context.... Perhaps we could get rid of it completely. We are not following REST semantics completely, anyway... Just `/metric/labelname/labelvalue/labelname/labelvalue/...` Then every path starting with `/metric/jobs` would go to the old API, everything else to the new, and if no job label is part of it, the push would fail....

**Comment by juliusv** [comment]
The latter might actually be a good idea, because it allow API compatibility for a while (less frustrated people who are already using the pushgateway).

Then for the new format, `job` wouldn't even have to come first, it just needs to be present somewhere in the URL?

**Comment by brian-brazil** [comment]
> Then for the new format, job wouldn't even have to come first, it just needs to be present somewhere in the URL?

I guess so, though I wouldn't go out of our way to implement it like that.

**Comment by beorn7** [comment]
Implementation wise, it probably doesn't matter at all. I put everything in a map, anyway.

OK, I guess I'll make it so. (No pluralization in the new API, any order, `job` must be somewhere. `/metrics/jobs` triggers the old syntax, if you want `jobs` as a real label name, you simply don't put it first.)

**Comment by beorn7** [comment]
Working on this now. 

I'll require to have `job` (or `jobs`) as the first part of the URL after all. Clearer distinction between new and old API. And makes the requirement for a job label clearer, too.
