### ISSUE TITLE
Pushgateway Persisted file cleanup

### ISSUE THREAD

**Issue by RamanPndy** [prometheus/pushgateway#320]
## Feature request
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
I've one docker image of pushgateway and one of Prometheus and prometheus in scraping from pushgateway in every 15 seconds. Now I've pushed 2 metrics in pushgateway and those metrics were scraped by prometheus and metrics were also persisted in the file. Now for some time prometheus docker was stop for some reason but during that time 3 new metrics were pushed to the pushgateway. Now when prometheus started again it pulled all 5 metrics again.
**What did you expect to see?**
I am expecting that prometheus should always scrap new metrics from pushgateway or some mechanism that when prometheus go down already pushed metrics should be removed from the pushgateway persisted file. I am expecting a mechanism to prevent persisted file grow and i also don't want to lose the metrics which were not pushed to the prometheus.

Please suggest any workaround to fix this issue.

**What did you see instead? Under which circumstances?**
on prometheus start it's not getting latest metrics from pushgateway and pushgateway metric file always grows and not removing already pushed metrics.

**Environment**
Ubuntu 16
Prometheus and Pushgateway latest docker images
* System information:

Linux 4.4.0-171-generic x86_64

* Pushgateway version:

pushgateway latest docker image

* Pushgateway command line:
version: '2'
services:
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'
    pushgateway:
        image: prom/pushgateway
        command:
            - '--persistence.file=pushgateway-metrics'
            - '--persistence.interval=10s'
        ports:
            - '9091:9091'
    grafana:
        image: grafana/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_AUTH_OAUTH_AUTO_LOGIN=true
        depends_on:
            - prometheus
        ports:
            - "3000:3000"

* Logs:
```
Insert Pushgateway logs relevant to the issue here.
```

**Comment by beorn7** [comment]
I'm not quite sure I understand what you are requesting here.

Scrapes in the Prometheus world must never change the state of what Prometheus scrapes. There might be multiple Prometheus servers or even other entities scraping the endpoint. There is no notion of "this sample has been scraped, I can remove it now".

Please also have a look at the [non-goals section](https://github.com/prometheus/pushgateway#non-goals).

**Comment by RamanPndy** [comment]
Yes @beorn7 you're pointing to High Availability of Prometheus server and I agree with this point. My concern is to prevent the continued growth of the persisted file and looking for a mechanism to delete the old metrics without losing the new metrics so that Prometheus needs not to save same metrics again and again.

**Comment by beorn7** [comment]
Usually, whatever pushes metrics will override the existing metrics, please look at https://github.com/prometheus/pushgateway#put-method and https://github.com/prometheus/pushgateway#post-method . You can also delete pushed metrics explicitly, see https://github.com/prometheus/pushgateway#delete-method .
And as stated in the non-goals, there are no plans to implement a timeout for pushed metrics, after which they would disappear automatically.

**Comment by RamanPndy** [comment]
yeah got it. but can you please suggest some mechanism so that I can get the time at which metric is pushed/updated or deleted in the pushgateway?? I see there is a flag **push_time_seconds**. this flag is storing the time at which metric is updated successfully. is there any API from which I can get the value ?? Basically the problem is I am looking for a mechanism to prevent the continued growth of the persisted file without the loss of any metric and do not want when the Prometheus starts scraping again from the pushgateway, it will store all values again. is there any workaround can you please suggest ??

**Comment by beorn7** [comment]
You shouldn't micromanage pushed metrics in that way. But that's now a usage discussion. Which should happen on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
