### ISSUE TITLE
Broken Pushgateway UI through reverse proxy

### ISSUE THREAD

**Issue by RamanPndy** [prometheus/pushgateway#322]
## Feature request
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
I have setup Pushgateway using docker and tried to implement using reverse-proxy.
**What did you expect to see?**
Pushgateway UI should show flawlessly.
**What did you see instead? Under which circumstances?**
Nginx Configuration:
`worker_processes 1;

events { worker_connections 1024; }

http {

log_format compression '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $upstream_addr '
        '"$http_referer" "$http_user_agent" "$gzip_ratio"';

upstream example-pushgateway {
        server 130.147.136.40:9091;
}

upstream example-prometheus {
        server 130.147.136.40:9090;
}

server {
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        listen 8082;

        location /pushgateway/ {
            proxy_pass         http://example-pushgateway/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
            proxy_set_header   X-Forwarded-Proto http;
            }

        location /prometheus/ {
            proxy_pass http://example-prometheus/prometheus/;
        }
   }
}`

and ran  pushgateway using docker through command:
sudo docker run -d --name=pushgateway -p 9091:9091 prom/pushgateway '--persistence.file=pushgateway-metrics' '--persistence.interval=10s'

and ran nginx using command:
sudo docker build -f Dockerfile -t pgnginx .
sudo docker run -d --name pgnginx -p 8082:8082 pgnginx

but when i hit http://130.147.136.40:8082/pushgateway/

CSS is not loading with other javascript files. means static is not at all accessible by nginx for pushgateway.
**Environment**
latest pushgateway docker image
* System information:
Linux 4.4.0-171-generic x86_64

* Pushgateway version:
latest pushgateway docker image

* Pushgateway command line:
sudo docker run -d --name=pushgateway -p 9091:9091 prom/pushgateway '--persistence.file=pushgateway-metrics' '--persistence.interval=10s'

* Logs:
```
Insert Pushgateway logs relevant to the issue here.
```

**Comment by RamanPndy** [comment]
![image](https://user-images.githubusercontent.com/10138989/72986594-892b4500-3e0e-11ea-8794-c242b21c9086.png)

**Comment by beorn7** [comment]
You have to set `--web.external-url="http://130.147.136.40:8082/pushgateway/"`. And possibly your `proxy_pass` should get the `/pushgateway` part appended. See also https://www.robustperception.io/using-external-urls-and-proxies-with-prometheus .

If you have more configuration questions, please use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by pkmisma** [comment]
> CSS is not loading with other javascript files. means static is not at all accessible by nginx for pushgateway.

did you resolve this issue? I am also getting same error I have setup via helm charts
