### ISSUE TITLE
Allow persisting to S3

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/pushgateway#33]
Currently the pushgateway is a stateful service, if it's state was checkpointed to S3 say every 5 minutes it could be treated at a stateless service for the cost of a few cent a month and a small window of potential data loss.

**Comment by grobie** [comment]
You could just mount s3 as filesystem https://github.com/s3fs-fuse/s3fs-fuse

**Comment by brian-brazil** [comment]
My understanding is that S3 fuse isn't very reliable, that approach also wouldn't quite work on a cluster system like Mesos.

**Comment by juliusv** [comment]
Yeah, offering the option of persisting directly to some kind of remote FS would be nice. No opinion on whether that should be S3 or something else, but it seems reasonable.

**Comment by grobie** [comment]
Yeah, no questioning of the the intent of course. I can just imagine we'll end up implementing all kind of storage clients and was wondering if we can just somehow move the interface for that outside of the pgw itself. I don't have any production experience with fuse fs though.

**Comment by ihr** [comment]
The use of FUSE is not always possible, especially in PaaS environments. As in order to mount the FUSE FS, you need two things (at least)

- the fuse device to be whitelisted 
- a SYS_ADMIN kernel capability which might be disabled (as in the case of CloudFoundry)

A plugable approach seem better idea, something similar to the [InfluxDB Telegraf Output Plugins](https://github.com/influxdata/telegraf#output-plugins)

**Comment by brian-brazil** [comment]
One option would be to have the state on disk always be consistent, and leave it up to the user to have a cronjob or whatnot doing the synchronisation.

**Comment by ihr** [comment]
You are right on that, when cronjob is possible. For distributed systems based on a PaaS, I'm afraid that is not always possible.

**Comment by beorn7** [comment]
I'd be very reluctant to put code into the Pushgateway that solves the problem for S3 specifically. I'd be even more reluctant to add a sophisticated output plugin system into this relatively lean code base with a well defined purpose. (It would easily become more complicated than the whole Pushgateway as it is now.)

At the current state of discussion, I'd recommend a side car to copy the snapshot out on a regular basis, or something similar (cron job, external job, wrapper, …).

Would it help to make the snapshot pull-able via an HTTP endpoint? That would be something I could imagine as a reasonable change.

**Comment by ihr** [comment]
Indeed, I see your point and it is a valid one. The Pushgateway has a very well defined purpose and its code base is quite lean. As a snapshot pull-able version of the gateway would still face the problem of non-persistent environments (loosing the metrics data if the container restarts), such as some PaaS, would it make sense to create a separate version with a more functionality?

**Comment by beorn7** [comment]
I don't understand how some PaaS's make it impossible to have a side-car or a wrapper, so I cannot really comment if those PaaS justify creating a special Pushgateway just for them.

**Comment by ihr** [comment]
As docker is highly adopted these days for application deployment, sometimes is simply unreasonable to run a side-car process within the same container. On other hand, scaling the gateway on PaaS without a persistent file system makes it prone to data lost and routing gets complicated as it requires the composition of dynamic headers. Big enterprises adopting these PaaS solutions would be highly interested in Prometheus which can provide high availability by offloading the metrics in a clustered persistent storage. Of course, such enterprises can adopt other monitoring solutions but I believe it would not be in the interest of Prometheus. Would you agree with that?

**Comment by beorn7** [comment]
Side-car implies running multiple containers, see pods in Kubernetes.

I still don't get why you cannot create a container that executes a script which first copies the snapshot from a distributed file storage, then starts Pushgateway, and after Pushgateway's shutdown copies the snapshot back to the distributed file storage.

**Comment by brian-brazil** [comment]
> scaling the gateway

The pgw is intended for service-level batch jobs. You should never need to worry about scaling that.

> Prometheus which can provide high availability by offloading the metrics in a clustered persistent storage

That's unrelated to the pushgateway, I suggest a read ofhttps://prometheus.io/docs/practices/pushing/

**Comment by ihr** [comment]
Thank you, you are both right. All the best.

**Comment by brian-brazil** [comment]
Looking at the source, the persistence file is already atomically updated so we already have the required support.
