### ISSUE TITLE
How to send counter type metric [help needed]

### ISSUE THREAD

**Issue by xinzhang** [prometheus/pushgateway#355]
Hi, I just don't understand how can I send counter type metrics to pushgateway.
For example, when there is an existing counter value as 8,  then when sending the data such as 
some_metric{label="val1"} 42
The 42 will be just overwritten to the current metric value and prometheus will take it as 42.
As counter, would it be able to add the current 8 with 42 and make the current metric as 50?
Or else the current counter is very similar to the gauge but it is integer.
Is there any way to achieve what I described? thanks.

**Comment by beorn7** [comment]
The Pushgateway is _not_ a distributed counter, see 2nd paragraph of the [non-goals section](https://github.com/prometheus/pushgateway#non-goals).
