### ISSUE TITLE
UI: Metrics text alignment issue on zoom

### ISSUE THREAD

**Issue by belm0** [prometheus/pushgateway#362]
## Bug Report
**What did you do?**
View Metrics UI with a zoom percentage in browser

**What did you expect to see?**
normal display metrics items

**What did you see instead? Under which circumstances?**
some metric items with long text are center-aligned rather than left-aligned

![Screen Shot 2020-07-29 at 11 44 56 AM](https://user-images.githubusercontent.com/1708631/88750913-7ca6f100-d191-11ea-9ae7-5ca329ae4282.png)

**Environment**

* Pushgateway version:

v1.2.0

**Comment by chunmeng** [comment]
Is inserting style attribute to the specific buttons acceptable?

![image](https://user-images.githubusercontent.com/2604020/95012079-185c4e00-0668-11eb-97d9-6bcd512fce73.png)

**Comment by beorn7** [comment]
Closing as the ad-hoc solution should fix the problem at hand. Of course, if some web expert has a cleaner solution, I'm all ers.
