### ISSUE TITLE
Details 


### ISSUE THREAD

**Issue by perbie** [prometheus/pushgateway#367]
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether f2:00:2c:44:c6:0b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::f000:2cff:fe44:c60b/64 scope link 
       valid_lft forever preferred_lft forever
8: rmnet_ipa0: <UP,LOWER_UP> mtu 2000 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/[530] 
21: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000
    link/ether c0:d2:dd:65:80:f3 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.148/24 brd 10.0.0.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 2601:1c0:4f00:390:9d4b:55d3:2df6:32df/64 scope global temporary dynamic 
       valid_lft 298sec preferred_lft 298sec
    inet6 2601:1c0:4f00:390:c2d2:ddff:fe65:80f3/64 scope global dynamic mngtmpaddr 
       valid_lft 298sec preferred_lft 298sec
    inet6 fe80::c2d2:ddff:fe65:80f3/64 scope link 
       valid_lft forever preferred_lft forever
23: p2p0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 3000
    link/ether c2:d2:dd:65:80:f3 brd ff:ff:ff:ff:ff:ff
24: tun0: <POINTOPOINT,UP,LOWER_UP> mtu 4096 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 10.1.10.1/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::da23:4f6b:947f:975a/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever

**Comment by beorn7** [comment]
Seems spam.
