### ISSUE TITLE
Makefile requires go-bindata but doesn't install it

### ISSUE THREAD

**Issue by discordianfish** [prometheus/pushgateway#37]
Related to #29

**Comment by beorn7** [comment]
Actually, it does... Can you tell me how to reproduce the problem?

**Comment by discordianfish** [comment]
@beorn7 TBH, no idea how I ran into it. I'll close this and reopen if I run into again. Didn't provide more details because I though we simply forgot to install it.

**Comment by beorn7** [comment]
I think @jcftang reproduced it. I guess if the go tool in .deps is used, go-bindata gets installed there and not into GOPATH, or something. Has to be investigated. Output:

jtang@awesome-o-w:[(none)@master]pushgateway$ make
GOROOT=/Users/jtang/develop/pushgateway/.deps/go GOPATH=/Users/jtang/develop /Users/jtang/develop/pushgateway/.deps/go/bin/go get -d
GOROOT=/Users/jtang/develop/pushgateway/.deps/go GOPATH=/Users/jtang/develop /Users/jtang/develop/pushgateway/.deps/go/bin/go get github.com/jteeuwen/go-bindata/...
/Users/jtang/develop/bin/go-bindata resources/
make: /Users/jtang/develop/bin/go-bindata: No such file or directory
make: *** [bindata.go] Error 1
jtang@awesome-o-w:[(none)@master]pushgateway$ git describe
fatal: No annotated tags can describe 'eefacc22c6a9b6393dde154804d65094cd54b3ed'.
However, there were unannotated tags: try --tags.

**Comment by jcftang** [comment]
I had some issues with installing go-bindata on OSX, I've yet to try on a debian/ubuntu box.

**Comment by beorn7** [comment]
https://github.com/prometheus/pushgateway/pull/40 should really solve this...
