### ISSUE TITLE
Pushgateway: allow for optional delete of metric upon scraping

### ISSUE THREAD

**Issue by dbabits** [prometheus/pushgateway#371]
## Feature request
**Use case. Why is this important?**
I have read #19 discussion and many others on the topic of TTL in pushgateway. 
This proposal is slightly different: [optionally] remove the metric when it's been read (probably by Prometheus)
My use case and seemingly many other people's call for it.
As it is, I have to jump through hoops to works around the issue of metric still showing as current in Prometheus long after it's been pushed to PG

**Comment by beorn7** [comment]
It's a fundamental property of Prometheus metrics endpoints that a scrape doesn't change the state of the metrics.

For example, in a Prometheus HA setup, two identically configured Prometheus servers scrape the same metrics endpoint. The one server in such an HA pair would trigger the removal of the metric in your proposal, and the other server would then not see it anymore.

If you need a "delete after scraping once"  behavior, that's a strong hint that you are actually doing event processing, for which Prometheus is not the right choice.

If you have more questions about your use case and how to implement (or perhaps better not to implement) it with Prometheus, I recommend the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).

**Comment by gw0** [comment]
I would argue that instead of rejecting a meaningful solution to a common problem of many Pushgateway users, a warning should be added that this is not compatible with for a Prometheus HA setup. Or there could be an option for how many scrapes are allowed before deleting a metric.

**Comment by Raven888888** [comment]
Agree with @gw0 , request for reopen
