### ISSUE TITLE
Deletion via the UI doesn't handle empty label values in the grouping key

### ISSUE THREAD

**Issue by c0llins0** [prometheus/pushgateway#375]
When one of the grouping keys is an empty string, the pushgateway does not allow me to delete the group.

I have tried this using the Web UI or by HTTP API request.

**Comment by beorn7** [comment]
You have to use base64 encoding for empty labels, that's [documented here](https://github.com/prometheus/pushgateway#url).

If you have further questions how to use base64 encoding, please use the [community support channels](https://prometheus.io/community/).

**Comment by c0llins0** [comment]
Thank you, I'll try that in the HTTP API.

Regardless, this issue still applies for the Web UI - it doesn't delete groups with an empty grouping key, I get an error: `Deleting metric group failed: Bad Request`.

**Comment by beorn7** [comment]
That's a good point. Let me investigate that. It would be a bug indeed.

**Comment by beorn7** [comment]
OK, I could reproduce the problem. (The empty label has to end up in the middle of the URL to trigger it. That's why it didn't show up when I tried it originally.)
