### ISSUE TITLE
Pushgateway metrics disappearing periodically with PUT

### ISSUE THREAD

**Issue by gotoworld** [prometheus/pushgateway#376]
**What did you do?**

Multi Application Instance push metrics (Counter) to pushgateway with PUT/POST (pushAdd/push), 

When the metrics with same name BUT different label values,  although we use PUT (pushAdd),  in multi application install model,  some of this metrics will be remove by mistake。

**What did you expect to see?**

When use PUT(pushAdd) method to push data for Pushgateway,  a metrics BUT different label values will not be removed,  anywhen a  metrics with SAME label values will be replaced.

**What did you see instead? Under which circumstances?**

![image](https://user-images.githubusercontent.com/8605471/101857152-d557b300-3ba1-11eb-810e-950b5290ba9f.png)

## Current Logic
---
a POST request replaces **all** metrics with the same name (in the group you push to) with the metrics you push. 
a PUT is that the latter replaces all metrics in the group by the metrics pushed.

## Expect Logic
---
a POST request replaces **Only, not ALL (X)** metrics with the same name (in the group you push to) with the metrics you push. 
       (**not All, But the metrics with same label values**)

a PUT is that the latter replaces all metrics in the group by the metrics pushed.

**Comment by beorn7** [comment]
I'm afraid we cannot change the logic right now. That would require a major version bump as it breaks everyone expecting the current logic.

I'm also not sure your feature request is really necessary. If your metrics have different labels, and you want them to exist independently, you can just use the labels that differ as part of the grouping key, and you are good.

**Comment by beorn7** [comment]
Based on the lack of follow-up, I assume that my explanation above is sufficient and close this issue. Feel free to follow up with contrary evidence.
