### ISSUE TITLE
prometheus pull metrics from pushgateway failed

### ISSUE THREAD

**Issue by akzj** [prometheus/pushgateway#380]
## Feature request
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

Linux 3.10.0-514.el7.x86_64 x86_64

* Pushgateway version:

pushgateway, version 1.3.0 (branch: HEAD, revision: c28992c985ce6c4fcf4247ba9736b72a3d43882f)
  build user:       root@cf69166ae53e
  build date:       20201001-12:03:34
  go version:       go1.15.2
  platform:         linux/amd64

* Pushgateway command line:

		Insert full command line.

* Logs:
```
level=error ts=2020-12-23T03:15:17.549Z caller=main.go:56 msg="error encoding and sending metric family: write tcp 10.53.134.26:9091->10.53.134.26:35438: write: broken pipe\n"
level=error ts=2020-12-23T03:15:32.962Z caller=main.go:56 msg="error encoding and sending metric family: write tcp 10.53.134.26:9091->10.53.134.26:36462: write: broken pipe\n"
level=error ts=2020-12-23T03:16:01.879Z caller=main.go:56 msg="error encoding and sending metric family: write tcp 10.53.134.26:9091->10.53.134.26:36606: write: broken pipe\n"
level=error ts=2020-12-23T03:16:17.566Z caller=main.go:56 msg="error encoding and sending metric family: write tcp 10.53.134.26:9091->10.53.134.26:37092: write: broken pipe\n"
```

**Comment by beorn7** [comment]
This looks like something on the network or the Prometheus server itself has cut the connection. My wild guess is that your Prometheus server has reached the scrape timeout. What's the message on the Prometheus server side? (Check out the Status → Targets page in the Web UI.)

**Comment by beorn7** [comment]
Assuming this is resolved.
