### ISSUE TITLE
Wiping of thousands of groups is slow under load

### ISSUE THREAD

**Issue by throne-developer** [prometheus/pushgateway#384]
## Feature request
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
wipe data
**What did you expect to see?**
Fast completion
**What did you see instead? Under which circumstances?**
too slow
**Environment**
centos6
* System information:

		Insert output of `uname -srm` here.

* Pushgateway version:
1.3.1
		Insert output of `pushgateway --version` here.

* Pushgateway command line:

		Insert full command line.

* Logs:
```
time curl 'http://10.123.128.23:9091/api/v1/admin/wipe' -X PUT -H 'Connection: keep-alive' -H 'Content-Length: 0' -H 'Accept: */*' -H 'Origin: http://10.122.16.241' -H 'X-Requested-With: XMLHttpRequest' -H 'User-Agent: Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1' -H 'Referer: http://10.122.16.241/' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.9' --compressed --insecure

real	15m52.045s
user	0m0.009s
sys	0m0.021s

About 5000 groups are stored. When pushgateway is started, all data can be cleaned up quickly. However, after running for one or two days, the cleaning time is very slow and takes about 15 minutes
```

**Comment by beorn7** [comment]
How fast are your pushes, and how often do you push in your scenario?

Wiping is currently implemented simply as queuing a delete request for every single group. Deletions should be fairly fast, but since they share the same queue as potentially frequent and slow push request, I could see how it takes a while delete 5000 groups under load.

I guess this could be optimized, but note that the Pushgateway is really not designed for this amount of pushed metrics. You will probably run into other issues as well with this amount of pushed metrics, so I'm not sure if it is worth it to optimize the wipe request.

**Comment by throne-developer** [comment]
Thank you for your reply. I have several services that need to monitor business indicators. When the service is running, it can write indicator data at any time, and then send it to pushgateway every 30 seconds. Each time it sends about 1000-2000 requests, it will eventually generate 4000-5000 groups.


Prometheus collects pushgateway data and displays it in grafana. If the pushgateway data is not cleared regularly, some data indicators will be shown as a straight line in grafana.

So I added a crontab task, which empties the pushgateway every 20 minutes, and then I found that the emptying operation was very slow.

**Comment by beorn7** [comment]
This sounds like you should let Prometheus scrape your service instances directly.

**Comment by throne-developer** [comment]
My services are deployed in k8s, only one port can be exposed, so they cannot be collected by Prometheus.

Recently, I wrote an explorer instead of pushgateway, so this problem can be closed.

**Comment by beorn7** [comment]
Just for the record: K8s allows multiple ports. Many users of Prometheus expose a separate port for Prometheus to scrape. But if you have only one port, and it's an HTTP port, you could expose the metrics via a separate path. That's even more common.
