### ISSUE TITLE
Restore "Prometheus Client Data Exposition Format" and make it read only

### ISSUE THREAD

**Issue by splitt3r** [prometheus/pushgateway#386]
Make https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY/edit?usp=sharing read only. Looks like some spammers used the document to be funny.

Or even better, make it a markdown document somewhere in this repo 😃

**Comment by beorn7** [comment]
Yeah, the document is in a sad state.

I don't even remember who owns it. I'll try to find out.
Most if it is still in https://prometheus.io/docs/instrumenting/exposition_formats/ . The only part that is missing is protobuf, but https://github.com/prometheus/client_model/blob/master/metrics.proto is kind of self-documenting.

**Comment by splitt3r** [comment]
Thx for the info

**Comment by beorn7** [comment]
We have found a team member that still had access to the document. It is now cleaned up. Thanks for bringing this to our attention.
