### ISSUE TITLE
Feature request: Multi-thread support

### ISSUE THREAD

**Issue by liangli1213** [prometheus/pushgateway#402]
There is some restriction on our Linux server, so we can't start exporter to expose metrics, as a workaround, we use a script to collect metrics then push to Pushgateway server, the cronjob is running every one minute.
We notice that Pushgateway maybe (I'm not sure) a single thread application, we have 1000 clients, and for each client, the pushing will hang about 4 minutes, after we setup 3 pushgateway daemon and group clients to 3, the pushing time reduce to 12s.
Actually speaking, we don't want to use multiple pushgateway deamon, since it bring us extra coding work, but we really want to know what is the bottle-neck for a single pushgateway daemon, see below top command output, why pushgateway daemon not using CPU at best effort?
```
  1485 prometh+  20   0 1202388 535632   5720 S 114.6  3.3 739:41.58 pushgateway
  1770 prometh+  20   0  857740 202120   6612 S 111.6  1.2  50:35.21 pushgateway
  1628 prometh+  20   0  857996 201548   6796 S 110.3  1.2  50:18.23 pushgateway
```

**Comment by liangli1213** [comment]
I study it further, I suspect the TCP connection process maybe low efficient when there is high concurrent client situation happen.

**Comment by beorn7** [comment]
The PGW is not meant for this use case. Please use the community channels to discuss other ways of addressing your problem: https://prometheus.io/community/

**Comment by beorn7** [comment]
https://github.com/prometheus-community/PushProx may be helpful for your use case, but as said, details need to be discussed elsewhere.

Also note that using the PGW to allow push with Prometheus is not just a performance problem. There are loads of semantic problems, too (like inability to deal with metric inconsistencies, up-monitoring, staleness handling, …). That's why I like to keep the PGW simple and focused on what it is meant for.

**Comment by liangli1213** [comment]
@beorn7 , thanks for searching the URL to me, as I said in my post, we are not allowed to deploy any exporter (it will listen on port), so as a compromise, we have to use pushgateway.
I just want to dig it further, why when concurrent client is 100, the pushing consumed time is less than 1s, but when concurrent client is 300, the cost is 10s, does TCP connection consumed most of the time? or the data processing cost most?
