### ISSUE TITLE
CPU usage script  give: text format parsing error in line 1: invalid metric name.

### ISSUE THREAD

**Issue by VladimirIzmakov** [prometheus/pushgateway#405]
## Feature request
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**
no error message.
**What did you see instead? Under which circumstances?**
ext format parsing error in line 1: invalid metric name
**Environment**
doocker

docker-compose.yml

version: '3.2'
services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
      - '--collector.diskstats.ignored-devices="^(ram|loop|fd|(h|s|v)d[a-z]|nvme\\d+n\\d+p)\\d+$$"'
    ports:
      - "19991:9100"

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    ports:
      - "19992:9091"

* System information:
Linux 5.4.0-1047-aws x86_64
* Pushgateway version:
/pushgateway $ pushgateway --version
pushgateway, version 1.4.0 (branch: HEAD, revision: 007ba874bead1b9ad2253d89e3adeb16a73fd012)
  build user:       root@410bc05a48f6
  build date:       20210122-23:54:24
  go version:       go1.15.7
  platform:         linux/amd64
/pushgateway $ 
* Pushgateway command line:
use script:

#!/bin/bash

# https://devconnected.com/monitoring-linux-processes-using-prometheus-and-grafana/

z=$(ps aux)
while read -r z
do
   var=$var$(awk '{print "cpu_usage_metric {process=\""$11"\", pid=\""$2"\"}", $3z}');
done <<< "$z"

echo  $var
curl -X POST -H 'Content-Type: text/plain' --data '$var' http://localhost:19992/metrics/job/top/instance/machine

after script execution getting:
text format parsing error in line 1: invalid metric name

idea is collect ps aux results and push to pushgatway and get  later from remote prometheus .

**Comment by beorn7** [comment]
The error message means that your script creates invalid metrics. This is not a bug in Pushgateway, but in your script.

If you want help using the Pushgateway, please use the [community channels](https://prometheus.io/community/).

As a side note, the tutorial you have linked isn't following the recommended usage pattern for the Pushgateway. Have a look at https://github.com/ncabatoff/process-exporter for a more "Promethean" approach to the problem.
