### ISSUE TITLE
Cannot pass parameters that hold no value in the chart ( web.enable-admin-api )

### ISSUE THREAD

**Issue by alexandrupetrini** [prometheus/pushgateway#410]
```
         {{- range $key, $value := .Values.pushgateway.extraArgs }}
            - --{{ $key }}={{ $value }}
```
Helm chart limititations or comand-line limitations  regarding flags that don't accept values make options like web.enable-admin-api not available in Kuberenetes

**Comment by beorn7** [comment]
I'm not sure what action you are suggesting here.

The Pushgateway is using Kingpin flags, which are widely used throughout the Prometheus ecosystem and, I'm sure, by many other projects.

**Comment by beorn7** [comment]
Closing for lack of follow-up.
