### ISSUE TITLE
How to push specific metrics and not all metrics.

### ISSUE THREAD

**Issue by KunalBurangi** [prometheus/pushgateway#412]
Here is the use case,
There are two types of metrics 
1) Default metrics
2) Custom Metrics

what I want to do is just want to push the custom metrics via push gateway and not the default metrics. can we do that? 
if yes how? 

I have tried to use the registers, but how do view values of different registers?
or can we push metrics from a particular register? 

is there any way to solve this use case?

**Comment by beorn7** [comment]
To quote the issue template (which you got presented with when filing the issue):

	Note that we use GitHub issues for bugs and (uncontroversial) feature
	requests (see below for details).

	Please do *NOT* ask usage questions in GitHub issues.  Usage questions make
	most sense on the users mailing list, where more people are available to
	potentially respond to your question, and the whole community can benefit
	from the answers provided (perhaps your question has already been answered,
	search the archive to find out):
	https://groups.google.com/forum/#!forum/prometheus-users
	[...]
	You can find more information at: https://prometheus.io/community/
