### ISSUE TITLE
High memory useage And Socket usage surges

### ISSUE THREAD

**Issue by ZChunnian** [prometheus/pushgateway#414]
Flat | Flat% | Sum% | Cum | Cum% | Name | Inlined?
-- | -- | -- | -- | -- | -- | --
41982.27MB | 34.55% | 34.55% | 46471.84MB | 38.25% | github.com/prometheus/common/expfmt.(*TextParser).readingValue |  
30931.19MB | 25.46% | 60.01% | 33865.24MB | 27.87% | github.com/prometheus/common/expfmt.(*TextParser).startLabelName |  
17575.90MB | 14.47% | 74.48% | 17575.90MB | 14.47% | bytes.(*Buffer).String | (inline)
16396.25MB | 13.50% | 87.97% | 16408.75MB | 13.51% | github.com/prometheus/common/expfmt.(*TextParser).readingMetricName |  
6692.60MB | 5.51% | 93.48% | 15646.85MB | 12.88% | github.com/prometheus/common/expfmt.(*TextParser).startLabelValue |  
2778.32MB | 2.29% | 95.77% | 3439.34MB | 2.83% | github.com/prometheus/common/expfmt.(*TextParser).setOrCreateCurrentMF |  
1675.80MB | 1.38% | 97.15% | 1675.80MB | 1.38% | bufio.NewWriterSize | (inline)
1163.93MB | 0.96% | 98.10% | 1163.93MB | 0.96% | bufio.NewReaderSize | (inline)
296MB | 0.24% | 98.35% | 838.02MB | 0.69% | github.com/prometheus/common/expfmt.(*TextParser).readingHelp |  
107.52MB | 0.09% | 98.44% | 1080.18MB | 0.89% | net/http.(*conn).readRequest |  
39MB | 0.03% | 98.47% | 117123.08MB | 96.40% | github.com/prometheus/pushgateway/handler.Push.func1 |  
23.50MB | 0.02% | 98.49% | 120789.10MB | 99.42% | net/http.(*conn).serve |  
20.50MB | 0.02% | 98.51% | 117384.28MB | 96.61% | github.com/prometheus/common/route.(*Router).handle.func1 |  
1.50MB | 0.00% | 98.51% | 3438.84MB | 2.83% | github.com/prometheus/common/expfmt.(*TextParser).startComment |  
0 | 0.00% | 98.51% | 117384.28MB | 96.61% | net/http.serverHandler.ServeHTTP |  
0 | 0.00% | 98.51% | 1675.80MB | 1.38% | net/http.newBufioWriterSize |  
0 | 0.00% | 98.51% | 1162.93MB | 0.96% | net/http.newBufioReader |  
0 | 0.00% | 98.51% | 117175.76MB | 96.44% | net/http.HandlerFunc.ServeHTTP | (partial-inline)
0 | 0.00% | 98.51% | 117384.28MB | 96.61% | net/http.(*ServeMux).ServeHTTP |  
0 | 0.00% | 98.51% | 117159.09MB | 96.43% | github.com/prometheus/pushgateway/handler.Push.func2 |  
0 | 0.00% | 98.51% | 117384.28MB | 96.61% | github.com/prometheus/common/route.(*Router).ServeHTTP |  
0 | 0.00% | 98.51% | 117004.56MB | 96.30% | github.com/prometheus/common/expfmt.(*TextParser).TextToMetricFamilies |  
0 | 0.00% | 98.51% | 117159.09MB | 96.43% | github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func2 |  
0 | 0.00% | 98.51% | 117158.58MB | 96.43% | github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2 |  
0 | 0.00% | 98.51% | 117158.58MB | 96.43% | github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1 |  
0 | 0.00% | 98.51% | 117384.28MB | 96.61% | github.com/julienschmidt/httprouter.(*Router).ServeHTTP |  
0 | 0.00% | 98.51% | 1163.93MB | 0.96% | bufio.NewReader

**Comment by beorn7** [comment]
This looks like your Pushgateway is very busy parsing metrics pushed to it.

How often are you pushing to the Pushgateway? How many metrics do you have in each push? How many metrics are alive on the Pushgateway at any given time?

Note that the Pushgateway is only designed to keep a few metrics (like hundreds or thousands) in memory. Pushing is supposed to be a rare event (much less often than scraping). The Pushgateway is not designed to turn Prometheus into a push-based monitoring system. See also https://prometheus.io/docs/practices/pushing/ .

**Comment by beorn7** [comment]
Closing for lack of follow up.
