### ISSUE TITLE
Feature: Allow overide of "instance" label

### ISSUE THREAD

**Issue by nhatfield** [prometheus/pushgateway#420]
Can you allow the ability to overide the `instance` label? This should give users the ability to push a single metric name, for many instances. For example:

server 1:  metric.test=1
server 2: metric.test=2

to allow prometheus to map both servers using the same metric name. This is to mimic the default behavior of node exporter allowing the user to select a query in grafana, `metric.test` and the values should show up from both `server1` and `server2`

**Comment by beorn7** [comment]
Not sure I understand your question completely.

Have you read [the section about the job and the instance labels](https://github.com/prometheus/pushgateway#about-the-job-and-instance-labels)? If you configure your Prometheus server to scrape the Pushgateway with `honor_labels: true`, the `instance` label pushed to the Pushgateway will prevail (or, if you have not pushed an `instance` label, there won't be any `instance` label after ingestion).

**Comment by nhatfield** [comment]
@beorn7 i think this is exactly what i need.... would that allow me to send in metrics on the same name but with different instance tags so I can query a single metric in grafana and see all of the "instances" reporting that metric?. Also how do I set this flag when i start the docker container? I dont see it in the doc 

Thanks

**Comment by beorn7** [comment]
I'll convert this to a discussion in the "Q&A" section, because that's a better fit. (It's not a feature request, after all…) See you on the other side!
