### ISSUE TITLE
Add support for backfill

### ISSUE THREAD

**Issue by nhatfield** [prometheus/pushgateway#446]
## Feature request

We should have the ability to fill in historical data points when recovering from disasters of some sort. Prometheus supports this already by appending the epoch to the metric line https://github.com/prometheus/prometheus/pull/7586. My proposal is to be able to send metrics in the same format as it is in this PR:

```
collectd_df_complex{host="myserver.fqdn.com",df="var-log",dimension="free"} 5.8093906125e+10 1582226100000
collectd_varnish_derive{host="myserver.fqdn.com",varnish="request_rate",dimension="MAIN.client_req"} 2.3021666667e+01 1582226100000
collectd_df_complex{host="myserver.fqdn.com",df="var-log",dimension="free"} 5.8093906125e+10 1582226100000
collectd_load{host="myserver.fqdn.com",type="midterm"} 0.0155 1582226100000
collectd_varnish_derive{host="myserver.fqdn.com",varnish="request_rate",dimension="MAIN.client_req"} 2.3021666667e+01 1582226100000
collectd_load{host="myserver.fqdn.com",type="midterm"} 1.5500000000e-02 1582226100000
collectd_varnish_derive{host="myserver.fqdn.com",varnish="request_rate",dimension="MAIN.cache_hit"} 3.8054166667e+01 1582226100000
collectd_df_complex{host="myserver.fqdn.com",df="var-log",dimension="free"} 5.8093906125e+10 1582226100000
collectd_varnish_derive{host="myserver.fqdn.com",varnish="request_rate",dimension="MAIN.s_pipe"} 0 1582226100000
collectd_varnish_derive{host="myserver.fqdn.com",varnish="request_rate",dimension="MAIN.cache_hit"} 3.8054166667e+01 1582226100000
collectd_load{host="myserver.fqdn.com",type="shortterm"} 1.1000000000e-02 1582226100000
collectd_varnish_derive{host="myserver.fqdn.com",varnish="request_rate",dimension="MAIN.client_req"} 2.3021666667e+01 1582226100000
collectd_load{host="myserver.fqdn.com",type="shortterm"} 1.1000000000e-02 1582226100000
collectd_load{host="myserver.fqdn.com",type="shortterm"} 1.1000000000e-02 1582226100000
collectd_load{host="myserver.fqdn.com",type="longterm"} 2.5500000000e-02 1582226100000
collectd_varnish_derive{host="myserver.fqdn.com",varnish="request_rate",dimension="MAIN.s_pipe"} 0 1582226100000
collectd_load{host="myserver.fqdn.com"type="longterm"} 2.5500000000e-02 1582226100000
collectd_varnish_derive{host="myserver.fqdn.com",varnish="request_rate",dimension="MAIN.cache_hit"} 3.8054166667e+01 1582226100000
collectd_load{host="myserver.fqdn.com",type="midterm"} 1.5500000000e-02 1582226100000
# EOF
```

**Use case**

To fill in historical data when recovering from a downed scenario. I have collectors that run and push metrics to the push gateway. The collectors have the ability to reach into the past, collect data, and can push to any backend source with their epoch timestamps. 

**Why is this important?**

1. because prometheus supports it and I would like to use prometheus products only, as the solution
2. because there is a real need to backfill data that is missed from power outages or other disaster recovery scenarios. Having a missed section of data throws off analytics and processing of data.
3. because it is one thing that you can do with other monitoring systems, that currently isnt supported on just the pushgateway for proetheus

Thanks

**Comment by beorn7** [comment]
I think you are misunderstanding how the Pushgateway works and what it is designed for. Backfilling through the Pushgateway is technically impossible with the current implementation (because the Pushgateway deliberately disallows timestamps on the metrics), but even if we lifted that restriction, it would be an extremely brittle and tedious procedure that we would strongly discourage anyway. (People have tried it before…)
