### ISSUE TITLE
http header Access-Control-Allow-Methods

### ISSUE THREAD

**Issue by tyagian** [prometheus/pushgateway#450]
If we can have support for http header Access-Control-Allow-Methods, we can avoid DELETE request by users. 
In current situation, if users have credentials to push metrics for which they don't need delete.

**Comment by beorn7** [comment]
If you can push metrics, you can effectively delete them by pushing an empty body for a grouping key.

Quoting the [README.md](https://github.com/prometheus/pushgateway#put-method): "A `PUT` request with an empty body effectively deletes all metrics with the specified grouping key. However, in contrast to the `DELETE` request described below, it does update the `push_time_seconds` metrics."
