### ISSUE TITLE
Flag to disable Web UI

### ISSUE THREAD

**Issue by tlinnyc** [prometheus/pushgateway#481]
## Feature request
**Use case. Why is this important?**
I'm worried about people going to the Web UI if they got the Pushgateway URL and possibly even accidentally hitting Delete Group on a metric. Rather than going through the hassle of blocking people or their machines (which may cause issues with pushing metrics), I'd like to see if it's possible just have the Web UI hidden, as I haven't really had the need to go there.

**Comment by beorn7** [comment]
The web UI is merely calling the API. Hiding the web UI would only be "security by obscurity". While I get the "by accident" part, you would need to restrict the whole API for actual security. (But note that the ability of pushing metrics is essentially equivalent to the ability to delete metrics, as you can push an empty set of metrics into a group.)

The Pushgateway is just a simple building block. For secure access rules, you need something around it (reverse proxy, ingress controller, whatever your environment requires).

In different news, the Pushgateway is meant to keep metrics in an ephemeral fashion (which is also the excuse for not having a elaborate permissions system on modifying metrics). There is no built-in redundancy or clustering or backup story. If hitting "Delete" causes actual trouble beyond temporary annoyances, the Pushgateway is probably not the right tool anyway.

In sum, if securing the pushed metrics data is your goal, I am concerned that hiding the web UI is actually a step into the wrong direction, providing just a false sense of security and disincentivizing a proper solution of your problem.

**Comment by tlinnyc** [comment]
Thanks, that makes sense. I'll do more research on reverse proxies and ingress controllers.
