### ISSUE TITLE
pushgateway  pull office exporter as gateway feature 

### ISSUE THREAD

**Issue by katechun** [prometheus/pushgateway#483]
## Feature request
**Case net firewall ,we need pushgateway as gateway **

*prometheus --pull--> pushgateway --pull--> office exporter*

**Comment by beorn7** [comment]
I'm afraid I don't quite understand the information provided.

The Pushgateway isn't meant to pull from anywhere. Are you perhaps looking for something like https://github.com/prometheus-community/PushProx ?

**Comment by beorn7** [comment]
Closing for lack of response. Feel free to respond here later, or use the [community channels](https://prometheus.io/community/), which are actually better suited for usage questions than GH issues.
