### ISSUE TITLE
Failed to view metrics on using pushgateway

### ISSUE THREAD

**Issue by vishalkalal22** [prometheus/pushgateway#493]
## Bug Report
**What did you do?**
I am trying to start the pushgateway on windows  10 OS using the command prompt.

**What did you expect to see?**
I am expecting to view the matrics on the 9091 port.

**What did you see instead? Under which circumstances?**

I am getting the below msg on the command prompt -

C:\Users\viskal71\Downloads\pushgateway-1.4.3.windows-amd64>pushgateway.exe
ts=2022-09-22T11:42:22.455Z caller=main.go:85 level=info msg="starting pushgateway" version="(version=1.4.3, branch=HEAD, revision=f9dc1c8664050edbc75916c3664be1df595a1958)"
ts=2022-09-22T11:42:22.455Z caller=main.go:86 level=info build_context="(go=go1.18.2, user=root@bc57578de81f, date=20220530-19:06:14)"
ts=2022-09-22T11:42:22.458Z caller=main.go:139 level=info listen_address=:9091
ts=2022-09-22T11:42:22.843Z caller=tls_config.go:195 level=info msg="TLS is disabled." http2=false

* Pushgateway version:

pushgateway-1.4.3 windows

* Pushgateway command line:

C:\Users\viskal71\Downloads\pushgateway-1.4.3.windows-amd64>pushgateway.exe

![image](https://user-images.githubusercontent.com/114053504/191739313-60e4fdbb-9a2c-4bf6-8974-ba89c7252491.png)

Request you to help me with this.

Thanks in advance !!!

**Comment by vishalkalal22** [comment]
Issue resolved

**Comment by sawyerwu** [comment]
>

hi @vishalkalal22 how you resolve this issue, I have the same problem here.
