### ISSUE TITLE
The untyped index cannot be deleted using the pushgateway api

### ISSUE THREAD

**Issue by wangchao732** [prometheus/pushgateway#499]
curl -X DELETE http://xxx:9091/metrics/job/spark-stream

pushgateway-1.4.3.linux-amd64

**Comment by wangchao732** [comment]
![微信图片_20221014113638](https://user-images.githubusercontent.com/19440083/195758453-670f0ff3-377f-49cb-9908-10a86d21fbc8.png)

**Comment by beorn7** [comment]
This seems to work just fine for me.

Are you sure you have pushed those metrics with the grouping key `job="spark-stream"`?

How does the web UI look like?
