### ISSUE TITLE
Prometheus Pushgateway : Add TTL (Time to live)

### ISSUE THREAD

**Issue by ErzaScarle** [prometheus/pushgateway#527]
Hi, it appears that a pushgateway doesn't support any form of TTL for the pushed metrics. Cache should be invalidated under the right circumstances and I think that introducing a TTL (e.g. with a "meta" label like: 'push_gateway_ttl_seconds') could help in removing cached stale metrics.

This issue is resolved already here : https://github.com/dinumathai/pushgateway
Can we add it to the main repo, so that we also get the latest updated pushgateway image with the TTL feature.

**Comment by nature1995** [comment]
I think this feature is very useful. We use shell script that call the admin api for delete the metric exceed the ttl.

**Comment by beorn7** [comment]
See the last paragraph in the [non-goals section](https://github.com/prometheus/pushgateway#non-goals).

**Comment by ErzaScarle** [comment]
Thank you.

**Comment by GavinZJZhang** [comment]
See pushgateway rewritten in Java, providing solutions to metrics expiration cause OOM and socket timeout network problems.

https://github.com/GavinZJZhang/dpushgateway
