### ISSUE TITLE
pushgateway restart anomaly

### ISSUE THREAD

**Issue by nature1995** [prometheus/pushgateway#528]
I got the same issue from https://github.com/prometheus/pushgateway/issues/407

System information:
Linux 3.10.0-1062.9.1.el7.x86_64 x86_64

Pushgateway version:
pushgateway, version 1.5.1 (branch: HEAD, revision: https://github.com/prometheus/pushgateway/commit/7afc96cfc5e2b278f3b20e56968ff30eea22b70e)
build user: root@fc81889ee1a6
build date: 20221129-16:30:38
go version: go1.19.3
platform: linux/amd64

Pushgateway command line:
./pushgateway --web.listen-address=:9091 --web.telemetry-path=/metrics --persistence.interval=15m --persistence.file=persistence-data --push.disable-consistency-check --web.enable-admin-api --web.enable-lifecycle --log.level=info

Logs:

Feb 06 01:47:11 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:47:11.281Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:34668: write: connection reset by peer\n"
Feb 06 01:48:07 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:48:07.756Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:54586: write: broken pipe\n"
Feb 06 01:48:38 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:48:38.139Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:39992: write: broken pipe\n"
Feb 06 01:49:08 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:49:08.431Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:58186: write: broken pipe\n"
Feb 06 01:49:38 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:49:38.762Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:60512: write: broken pipe\n"
Feb 06 01:50:09 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:50:09.058Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:46956: write: broken pipe\n"
Feb 06 01:50:39 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:50:39.371Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:47568: write: broken pipe\n"
Feb 06 01:51:09 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:51:09.607Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:40090: write: broken pipe\n"
Feb 06 01:51:23 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:51:23.407Z caller=diskmetricstore.go:221 level=info msg="metrics persisted" file=persistence-data
Feb 06 01:51:39 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:51:39.737Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:35444: write: broken pipe\n"
Feb 06 01:53:47 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:53:47.868Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:55806: write: connection reset by peer\n"
Feb 06 01:54:47 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:54:47.697Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:43206: write: broken pipe\n"
Feb 06 02:06:17 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T18:06:17.115Z caller=diskmetricstore.go:221 level=info msg="metrics persisted" file=persistence-data
Feb 06 02:21:22 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts

**Comment by nature1995** [comment]
Could you know how to solve this issue? @beorn7

**Comment by beorn7** [comment]
As said in #407, I suspect overload rather than a bug. Let's keep things in #407. If there is evidence this is a bug, we can re-open it. Otherwise, I recommend to get support via the [community channels](https://prometheus.io/community/).
