### ISSUE TITLE
Grouping labels should be validated

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/pushgateway#54]
While working on the java client, I managed to create a labelname of `a=b` which is not valid. The grouping labels should be checked for validity in push.go. It appears that the prometheus server is also not validating this on ingestion.

**Comment by jpittis** [comment]
#64 adds the proper validation to pg. This issue should be closed. If an issue similar to this one has not been created in the prometheus server repo, that should also be done.

**Comment by brian-brazil** [comment]
Thanks!

**Comment by beorn7** [comment]
I filed https://github.com/prometheus/prometheus/issues/1232 for the server.
