### ISSUE TITLE
 Increase configuration of whether the metric item expires (never/hour/day)

### ISSUE THREAD

**Issue by zyy4676** [prometheus/pushgateway#540]
Increase configuration of whether the metric item expires (never/hour/day)

*“Nice to have” is not a good use case. :)*

Just  push metric to pushgateway once , prometheus will be never-ending pull metric  from pushgateway to influxdb.  Duplicate data to influxdb is meaningless

**Comment by beorn7** [comment]
This is one of the non-goals, see last paragraph in the [non-goals section of the README.md](https://github.com/prometheus/pushgateway#non-goals).
