### ISSUE TITLE
Improve debug logging

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#55]
Currently, we don't use leveled logging at all in pushgateway.

The original idea was that the pushgateway is so simplistic, all the relevant information would be in the HTTP response.

As it turns out, clients tend to never display the body of an HTTP response with an error code.

For convenience, consider introducing leveled logging so that client-induced errors (invalid payload) are logged at a low level like INFO or DEBUG.

**Comment by beorn7** [comment]
While on it: If no persistence file is configured, the following is still logged:
`INFO[0300] Metrics persisted to ''.                      file=diskmetricstore.go line=156`
(But nothing is in fact persisted.)

**Comment by beorn7** [comment]
Yet another note: Warnings about inconsistent help strings can go rampant. They should be INFO level so that they can be disabled.

**Comment by Conorbro** [comment]
Should this be closed now? @beorn7 @brian-brazil

**Comment by beorn7** [comment]
Yeah, I guess we are good for now.
Thanks 1M.
