### ISSUE TITLE
Locking may cause the Push handler function to become single-threaded

### ISSUE THREAD

**Issue by Listson** [prometheus/pushgateway#565]
Why need to add a lock in the Push handler, this time causes the http request processing function to become a single thread
```
func Push(
	ms storage.MetricStore,
	replace, check, jobBase64Encoded bool,
	logger log.Logger,
) func(http.ResponseWriter, *http.Request) {
	var mtx sync.Mutex // Protects ps.

	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		...
		mtx.Unlock()

		...
	})

	...

	return func(w http.ResponseWriter, r *http.Request) {
		mtx.Lock()
		instrumentedHandler.ServeHTTP(w, r)
	}
}
```

**Comment by beorn7** [comment]
That mutex is indeed a leftover from older parameter handling. I'll prepare a PR to remove it.

However, since only the parameter retrieval is protected by the mutex, the performance impact will be very low. (Still, of course, it's much better to not have a confusing unneeded mutex here.)
