### ISSUE TITLE
Add a reload button at the homepage or auto reload

### ISSUE THREAD

**Issue by thiago-marafeli-VBL** [prometheus/pushgateway#568]
## Feature request
When using the web interface for Pushgateway, whenever we want to reload the page, we have to reload the whole page (F5), but this makes all the dropdowns retract and back to the top of the page. Then, we have to search and open it all over again to see the value we want. It would be great if there was a button to reload the results without changing the "point of view" or an auto-reload one like the Grafana's, staying just as it is instead of scrolling all the way to the top of the page.

A convenient use case is when we are testing Pushgateway to watch the values and see if they are showing as expected at the page, before being introduced in Prometheus or Grafana.

**Comment by ResamVi** [comment]
Hey I would take a crack at this for October - I'll look to add the reload button (auto-reload looks a bit advanced for now but could be a step for the next person)

**Comment by beorn7** [comment]
The accordions are now re-opened upon a reload (initiated via the usual means, F5, or Ctrl-R or whatever you do). Thanks @ResamVi . An auto-reload with configurable timing as in Grafana would also be nice, but maybe not as important as for a dashboard. I'll close this for now, but whoever feels like adding an auto-reload options, please go for it.
