### ISSUE TITLE
 High CPU Usage in checkWriteRequest Method of Storage Module

### ISSUE THREAD

**Issue by vbirds** [prometheus/pushgateway#598]
I've encountered a performance issue in the storage module, specifically with the checkWriteRequest method. This method appears to be consuming an unusually high amount of CPU resources. Here are the details:

![image](https://github.com/prometheus/pushgateway/assets/9044488/88424435-9aa0-4da4-9c15-f7737e5e3be2)

top info:
![img_v3_025m_40a46f74-d54c-4ce4-8e5f-03bd5a34b60g](https://github.com/prometheus/pushgateway/assets/9044488/d960fff6-0cc4-451d-89ee-7f8719af5dff)

**Comment by iKenApple** [comment]
hello, I also meet this problem. How do you solve this? by add --push.disable-consistency-check?

**Comment by iKenApple** [comment]
@vbirds thank you

**Comment by vbirds** [comment]
> hello, I also meet this problem. How do you solve this? by add --push.disable-consistency-check?

yes, add --push.disable-consistency-check
