### ISSUE TITLE
Persisting not happen properly.

### ISSUE THREAD

**Issue by bugcy013** [prometheus/pushgateway#60]
Hi Guys,

Have tried file based persistence not happen properly. but log says persisting

INFO[96978] Done checkpointing in-memory metrics and chunks in 278.893052ms.  file=persistence.go line=563
INFO[97278] Checkpointing in-memory metrics and chunks...  file=persistence.go line=539
INFO[97278] Done checkpointing in-memory metrics and chunks in 235.068046ms.  file=persistence.go line=563

start command ::

./pushgateway -persistence.file file -persistence.interval 1m0s

When I open actual web page I can see data.

Please let me know any further details log. etc.

**Comment by juliusv** [comment]
So you mean, when you restart the pushgateway, the metrics are gone from the web interface and from `/metrics`? Does the file `file` get created, and what is its size?

That works for me when I build from HEAD.

**Comment by bugcy013** [comment]
You are correct, When I restart metrics gone away.

file created 

~/pushgateway $ stat file
  File: ‘file’
  Size: 15614     	Blocks: 32         IO Block: 4096   regular file
Device: 812h/2066d	Inode: 4479432     Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/  sabari)   Gid: ( 1000/  sabari)
Access: 2015-10-08 14:27:16.964955875 -0400
Modify: 2015-10-08 14:22:51.516960807 -0400
Change: 2015-10-08 14:22:51.520960807 -0400
 Birth: -

Also I can see data in file
172.16.30.135job%run_id=138371,asset=BAC,date=20140103����!@!benchmark_read_time_secondsͨ�}"� �!benchmark_read_time_secondsinstance
172.16.30.136job%run_id=138371,asset=BAC,date=20140130�@��rk_read_time_secondsͨ�}'�9a�!benchmark_read_time_secondsinstanceinstancenstance
172.16.30.144job%run_id=138371,asset=BAC,date=20140110�@��!@!benchmark_read_time_secondsͨ�}�0��!benchmark_read_time_secondsinstancenstance

Am also build code from head


@juliusv one question, once data persistence to file, metric gone away right. /metric page ?

**Comment by juliusv** [comment]
That looks like the data is written to the persistence file correctly.

When you are shutting down the pushgateway and starting it up again, you are certain that you are starting it with the same persistence file flag again?

No, metrics should not disappear from the /metrics or status page once they are persisted. The persistence is only there so that you can restart the pushgateway and still retain metrics state across restarts.

**Comment by beorn7** [comment]
@bugcy013 The initial log lines you quoted are from the Prometheus server, not from the Pushgateway. Are you sure you are looking at the /metrics endpoint of the Pushgateway? (It is on port 9091 by default, e.g. `http://localhost:9091/metrics`.)

**Comment by beorn7** [comment]
Assuming this issue is resolved. Please re-open with more information if needed.
