### ISSUE TITLE
Basic setup of the pushgateway

### ISSUE THREAD

**Issue by GalaxyGorilla** [prometheus/pushgateway#61]
Hi, I built the pushgateway from git and started the binary as described. From my understanding one uses port 8080 for pushing the metrics using http and port 9091 to let prometheus pull them from the gateway. In my case the curl examples are not working. Netstat shows me no sign of usage for port 8080. I guess i do something fundamentally wrong here. It would be nice if someone can help me out :/.

**Comment by brian-brazil** [comment]
The pushgateway only uses one port, looks like our examples need updating.
