### ISSUE TITLE
pushgateway allways 504  Connection timed out and write queue is full

### ISSUE THREAD

**Issue by VinnyWan** [prometheus/pushgateway#627]
curl 172.23.29.50:9091/-/healthy
write queue is full
curl 172.23.29.53:9094/-/healthy
curl: (7) Failed connect to 172.23.29.53:9094; Connection timed out

NGINX upstream server is pushgateway cluster 
nginx use consistent_hash $http_x_real_ip config , 
Please take a look at this question.
thanks

**Comment by beorn7** [comment]
This sounds like you are overloading your PGW. Note that the PGW is designed to receive only a handful of metrics per push and keep hundreds or maybe thousands of metrics in its storage.

**Comment by beorn7** [comment]
For lack of follow-up, I assume that's the reason and close this.

If you have further evidence to report a bug, please follow up to this issue and I'll re-open.
