### ISSUE TITLE
/usr/local/bin/pushgateway --version.  to stderr

### ISSUE THREAD

**Issue by kunalmehta-eve** [prometheus/pushgateway#648]
Is there a good reason to have --version go to stderr? I've been trying to patch up some ansible roles to install pushgateway and I spend some time trying to figure out why I couldn't grab the output the other day.

So I wanted to make a ticket and ask.

I can confirm it's stderr (just wondering if this is maybe bug or intentional):

## Feature request
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**
  Output should be redirected to stdout not stderr

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

		Linux 6.5.0-35-generic x86_64

* Pushgateway version:

		
/usr/local/bin/pushgateway --version
pushgateway, version 1.8.0 (branch: HEAD, revision: 5aef87129c8d9ecebcc8b2fb0e97a31980680e8c)
  build user:       root@7f0b27f823b5
  build date:       20240403-17:11:45
  go version:       go1.22.1
  platform:         linux/amd64
  tags:             unknown

* Pushgateway command line:

		Insert full command line.

* Logs:
```

```

**Comment by beorn7** [comment]
No good reason. It's just the Kingpin default behavior. But the Prometheus server, also using Kingpin, changes the default behavior to stdout. I think we should be consistent within the Prometheus ecosystem.

#651 changes the behavior. Please have a look.
