### ISSUE TITLE
Docker container versioning not implemented

### ISSUE THREAD

**Issue by crisidev** [prometheus/pushgateway#66]
Hi,
I am using pushgateway and I would like to use the official prom/pushgateway container from docker hub.
The versioning system is not implemented and currently prom/pushgateway:latest contains pushgateway 0.2.0. Is it possible to push containers with a sane versioning system?

**Comment by beorn7** [comment]
@discordianfish We need Docket help! What is @crisidev talking about? :)

**Comment by crisidev** [comment]
I am speaking about the fact that prom/pushgateway docker containers on docker hub are pushed as just latest tag and not also with the correct version as tag. Example: current version of prom/pushgateway:latest is 0.2.0. Can you also push 0.2.0 as tag?

**Comment by fabxc** [comment]
Did the same as for node_exporter.

**Comment by crisidev** [comment]
Thanks!

**Comment by discordianfish** [comment]
@grobie: What are your plans with the binary builds? I was waiting for that with looking into how to fix this tagging issue properly.. Docker hub doesn't track remote tags which sucks.. We should either create our own images and push them to the hub - or switch things to quary.io which supports tacking of all tags.

**Comment by jimmidyson** [comment]
@discordianfish Docker hub can track git tags now, but only on new tag push. Mapping git tag name -> docker tag name.

**Comment by sdurrheimer** [comment]
This is fixed by #76. Future iteration of releases will have a sane docker image versioning.
- `master` tag for the latest commit in the `master`
- `x.x.x-x` tag for new pre-release
- `x.x.x` and `latest` tag for new release
