### ISSUE TITLE
Support line protocol for influxdb

### ISSUE THREAD

**Issue by mehrdad2000** [prometheus/pushgateway#666]
Hi
Is it possible to add influxdb format for output?
like this

current output
go_gc_duration_seconds{quantile="0"} 0.000208915

Line protocol format:
measurement,tag1=value1,tag2=value2 field1=value3,field2=value4 timestamp

Expected output
go_gc_duration_seconds,quantile="0" value=0.000208915 [1625487910](tel:1625487910)

More detail:
https://docs.influxdata.com/influxdb/v2/reference/syntax/line-protocol/

Thanks

**Comment by beorn7** [comment]
There should be tools somewhere that scrape a Prometheus endpoint and convert it into Influx line protocol.

There are no plans to support any exposition formats in the PGW beyond Prometheus and OpenMetrics.
