### ISSUE TITLE
Update Bootstrap version

### ISSUE THREAD

**Issue by mmolinac** [prometheus/pushgateway#674]
## Security Vulnerability Report
We noticed Bootstrap 4.3.1 is being used in the current Prometheus Pushgateway exporter release (1.9.0).
https://github.com/prometheus/pushgateway/tree/master/resources/static/bootstrap-4.3.1-dist

There is a publicly disclosed security vulnerability for Bootstrap - see https://security.snyk.io/package/npm/bootstrap/4.3.1 .

**What did you expect to see?**

It looks like the issue is fixed in versions later than 5.0.0.

**Environment**

* System information:

```Shell
Linux 5.10.0-31-cloud-amd64 x86_64
```

* Pushgateway version:

```Shell
# ./pushgateway --version
pushgateway, version 1.9.0 (branch: HEAD, revision: d1ca1a6a426126a09a21f745e8ffbaba550f9643)
  build user:       root@2167597b1e9c
  build date:       20240608-15:04:08
  go version:       go1.22.4
  platform:         linux/amd64
  tags:             unknown
```

* Pushgateway command line:

N/A

* Logs:

N/A

**Comment by beorn7** [comment]
Please report security issues privately as described in https://prometheus.io/docs/operating/security/ . While doing so, please pay attention to the [section about automated security scanners](https://prometheus.io/docs/operating/security/#automated-security-scanners). Thank you very much.
