### ISSUE TITLE
Where can I find logs?

### ISSUE THREAD

**Issue by fedotxxl** [prometheus/pushgateway#68]
Pushgateway returns `500` and I have no idea why. Where can I find logs?

**Comment by beorn7** [comment]
Pushgateway logs to stdout, but sparsely.

The error message for a failed HTTP request is usually returned in the body of the response. That's RFC-compliant, but apparently, some mainstream HTTP libraries (like Java standard library) make it really hard to read the body if an error code is returned.

See https://github.com/prometheus/pushgateway/issues/55 for details to improve the situation.

**Comment by fedotxxl** [comment]
Here is code from simpleclient:

````
int response = connection.getResponseCode();
if (response != HttpURLConnection.HTTP_ACCEPTED) {
        throw new IOException("Response code from " + url + " was " + response);
}
````

So `java simpleclient` doesn't provide this info / gateway doesn't log `5xx` messages...

**Comment by beorn7** [comment]
According to @brian-brazil , that's a restriction of the Java connection class.
