### ISSUE TITLE
-web.telemetry-path not honored for pushes

### ISSUE THREAD

**Issue by bluecmd** [prometheus/pushgateway#73]
Hi,

I'm using pushgateway behind a proxy served by /push/*.

For this I run:

```
/srv/pushgateway -web.telemetry-path=/push/metrics
```

This works just fine:

```
$ wget -O - http://localhost:9091/metrics | wc -l
2016-01-26 22:07:15 ERROR 404: Not Found.
0
$ wget -O - http://localhost:9091/push/metrics | wc -l
2016-01-26 22:07:21 (1.20 GB/s) - written to stdout [6777/6777]
118
```

But for pushing this is not the same:

```
$ echo "some_metric 3.14" | curl --data-binary @-  http://localhost:9091/metrics/job/some_job
$
$ echo "some_metric 3.14" | curl --data-binary @-  http://localhost:9091/push/metrics/job/some_job
404 page not found
```

**Comment by juliusv** [comment]
Yeah, `-web.telemetry-path` is only for the normal Prometheus metrics exposition endpoint, not the pushgateway API. However, we could consider supporting `-web.external-url` in the PGW as we do for Prometheus, which would allow you to prefix all path handlers.

**Comment by csawyerYumaed** [comment]
-web.external-url would be nice to have.
