### ISSUE TITLE
Metrics from different instances replace each other

### ISSUE THREAD

**Issue by fedotxxl** [prometheus/pushgateway#74]
We've got app on two servers. Each of them pushes data to pushgateway. We found out that metrics replaces each other. Looks like instance should be included into the `grouping key` but it's not clear how to do it.

Can you clarify this problem? We use java simple api.

**Comment by brian-brazil** [comment]
This doesn't sound like a service-level batch job, so the recommended way to do this is to scrape the two application servers directly.

`instanceIPGroupingKey()` is what you're probably looking for.

**Comment by juliusv** [comment]
Please also refer to this relevant documentation article about how and when to use the pushgateway, and avoiding such situations: https://prometheus.io/docs/practices/pushing/
