### ISSUE TITLE
Cut a new release ASAP to get sane docker images in docker hub and quay

### ISSUE THREAD

**Issue by quolix** [prometheus/pushgateway#79]
Deploying pushgateway (from Docker hub) in version 0.1.0 and 0.1.1 yields a 

  Asset template.html not found

on /.

**Comment by beorn7** [comment]
Is it working with 0.2.0 or 0.1.2?

**Comment by quolix** [comment]
No idea, not available on Docker hub:
https://hub.docker.com/r/prom/pushgateway/tags/

**Comment by beorn7** [comment]
Oops...

I'll check that once I find time. On quay.io, there is only master, but not the releases.

@sdurrheimer perhaps you already know what's going on and can beat me to it.

**Comment by sdurrheimer** [comment]
Indeed looks like `0.1.0` and `0.1.1` UI is not working. Those images are pretty old, `ubuntu` based ([Dockerfile](https://github.com/prometheus/pushgateway/blob/eefacc22c6a9b6393dde154804d65094cd54b3ed/Dockerfile)).

The `latest` tag is based on the `sdurrheimer/alpine-golang-make-onbuild` image. Works fine, and correspond to the 8e2fc3c commit ([Dockerfile](https://github.com/prometheus/pushgateway/blob/8e2fc3c520af73680d7030935359ad26772363a0/Dockerfile)).

The `master` tag uses the new release process, works fine. We should probably cut a `0.3.0` release.

**Comment by beorn7** [comment]
Cannot we just create a docker image for 0.2.0 on Docker hub and Quay?

**Comment by sdurrheimer** [comment]
By building it manually with the same commit as the release yes, but the [Dockerfile](https://github.com/prometheus/pushgateway/blob/add82b87568e03b1cc96f8a897219fc522dba08c/Dockerfile) is also based on the `ubuntu` version. We will probably hit the same problem.

`0.2.0` is pretty old (add82b8), lot of commits since. Given that we have the new release process now, it's better to cut a 0.3.0 release, which will also have pre-build binaries.

**Comment by beorn7** [comment]
I see. I'll simply cut 0.3.0 tomorrow-ish then. Thanks.

**Comment by sdurrheimer** [comment]
@beorn7 In case, this [comment](https://github.com/prometheus/collectd_exporter/pull/30#issuecomment-221343234) from @grobie explain how to trigger the release process, without forgetting to bump the version in the `VERSION` file.

I will definitely work on a short "How to cut a release" guide, the missing part for me is the git aspect given that all repos does not use a release branch etc.

**Comment by beorn7** [comment]
My idea on documentation is that we should document the `prometheus/prometheus` state and then try to make all other repositories as similar as possible and document the deviations in the respective repository.

**Comment by sdurrheimer** [comment]
@quolix A new release is [out](https://github.com/prometheus/pushgateway/releases/tag/0.3.0). Also available as `prom/pushgateway:0.3.0` and `quay.io/prometheus/pushgateway:0.3.0` docker images.

**Comment by quolix** [comment]
That was quick, awesome, thank you!
