### ISSUE TITLE
metrics expiry

### ISSUE THREAD

**Issue by zerthimon** [prometheus/pushgateway#83]
It'd be nice if there was a configuration parameter to specify how long the metric should "live" inside the pushgateway and then expie.

**Comment by brian-brazil** [comment]
This has been discussed previously, we will not be adding this feature. See #19

**Comment by zerthimon** [comment]
So, I was hoping I could alert on cron-based scripts used to backup stuff off my servers to a remote storage. I made each script send it's exit status to prometheus-pushgateway. It works well - I defined alert rules for a non-zero exit status. Now, how do I alert if the scripts crashes in the middle (or doesn't run at all) and therefore doesnt send it's exit code ? The pushgateway will reports the last status forever, so I'll never know there is a problem with the script.

**Comment by zerthimon** [comment]
P.S. I read the thread https://github.com/prometheus/pushgateway/issues/19 Is my solution for this use case an antipattern ? Why ? What's the prometheus-based best practice approach to monitoring cron script results ?

**Comment by brian-brazil** [comment]
http://www.robustperception.io/monitoring-batch-jobs-in-python/ explains how to do this from Python.

**Comment by zerthimon** [comment]
Ok, understood, additional metric for time of last success. Thanks @brian-brazil
