### ISSUE TITLE
Document the "distributed counter" non-goal

### ISSUE THREAD

**Issue by beorn7** [prometheus/pushgateway#87]
Quite often, people think of the Pushgateway as a distributed counter. Then they realize it's not doing that, and file a feature request.

We should make clear in the README.md that the PGW is not a distributed counter, and that the functionality might be something implemented as a stand-alone tool or (much less likely) as an additional feature in the PGW.

**Comment by beorn7** [comment]
Cf. https://groups.google.com/forum/?fromgroups#!topic/prometheus-developers/hbvukQp0J_E

**Comment by beorn7** [comment]
Hmmm... It's already there: "The Pushgateway is explicitly not an aggregator, but rather a metrics cache. It does not have a statsd-like semantics."

I'll simply make it even clearer and boldface or something.

**Comment by RSully** [comment]
For anyone landing here, this might be useful: https://github.com/messagebird/pushprom

**Comment by lyda** [comment]
Any chance this could be linked on the README? It's really helpful for smaller php projects.

**Comment by beorn7** [comment]
@lyda Happy to do so, but it would make more sense to (also) link it from the prometheus.io site. How about creating a PR on https://github.com/prometheus/docs ? This would also trigger a review by the custodians of the docs site, which would give us some confidence pushprom is doing the right thing. (I haven't looked closely at it so far.) We can then also link it from the Pushgateway's README.md. (PR welcome.)
