### ISSUE TITLE
Got protobuf decode error when sending protobuf type to pushgateway.

### ISSUE THREAD

**Issue by bangn** [prometheus/pushgateway#88]
Hi,

I'm trying to post a protobuf type of a counter metric to pushgateway.

Here is the code:
```
label_pairs = { "status" => "200", "method" => "GET" }

prometheus_metric = ::Io::Prometheus::Client::MetricFamily.new do |metric_family|
  metric_family.name = "test"
  metric_family.type = ::Io::Prometheus::Client::MetricType::COUNTER
  metric_family.metric = [
    ::Io::Prometheus::Client::Metric.new do |metric|

      metric.label = label_pairs.map do |name, value|

        ::Io::Prometheus::Client::LabelPair.new do |label_pair|
          label_pair.name = name
          label_pair.value = value
        end
      end

      metric.counter = ::Io::Prometheus::Client::Counter.new(:value => 1)
    end
  ]
end

EM.run do
  df = ::EventMachine::HttpRequest.new("http://localhost:9091/metrics/job/test_job").post(
    :head => {
      "Content-Type" => "application/vnd.google.protobuf; proto=io.prometheus.client.MetricFamily; encoding=delimited"
    },
    :body => prometheus_metric.encode
  )

  df.callback do |http|
    puts "Response status: #{http.response_header.status}"
    puts http.response
    EM.stop
  end

  df.errback do |e|
    puts "Fail!"
    puts e.error

    EM.stop
  end
end
```

And this is the error:

```
Response status: 500
proto: io_prometheus_client.MetricFamily: wiretype end group for non-group
```

I'm using protobuf file from this [proto](https://github.com/prometheus/client_model/blob/086fe7ca28bde6cec2acd5223423c1475a362858/metrics.proto)

Have anyone ever seen it?
How can I resolve it?

Thank you in advance.

Cheers,
Bang

**Comment by brian-brazil** [comment]
I'd recommend you use the text protocol, by using the Ruby client directly rather than having to worry about this implementation detail.

https://github.com/prometheus/common/blob/4402f4e5ea79ec15f3c574773b6a5198fbea215f/expfmt/decode.go#L88 is what's going on.

**Comment by bangn** [comment]
Hi Brian,

Thank you for your answer.

Our architecture relies on asynchronous code, therefore Ruby client could not be used.
We could use text format over protocol, however it would be greater to be able to use Protobuf though.

Cheers,
Bang

**Comment by juliusv** [comment]
Yeah, not sure if there's any Ruby support for delimited protobufs yet. It should be much easier to send the text format (best using the Ruby client lib), and there's no real downsides to that.

**Comment by bangn** [comment]
I thought prometheus/pushgateway support protobuf.

Is it a bug as pushgateway cannot decode protobuf format?

**Comment by juliusv** [comment]
The pushgateway supports protobuf, but you are not sending the correct protobuf format. Prometheus (and the pushgateway) expect a message of multiple protobuf messages which are delimited in a certain way. See: https://github.com/matttproud/golang_protobuf_extensions/blob/master/pbutil/encode.go#L24-L46

**Comment by juliusv** [comment]
So, if you *really* want to send protobufs instead of text format (you shouldn't), you will need to prefix your encoded protobuf with a 32-bit varint that indicates the length of the encoded message.

**Comment by juliusv** [comment]
Closing this, as this has nothing to do with the pushgateway.

**Comment by bangn** [comment]
It can be encoded as follow
```ruby
    data = prometheus_metric.encode
    encoded_data = "#{::Protobuf::Field::VarintField.encode(data.size)}#{[data].pack('a*')}"
```
