### ISSUE TITLE
Add documentation for adding release events

### ISSUE THREAD

**Issue by mikeparker** [prometheus/pushgateway#89]
In various graphing tools (such as Grafana), it is useful to tag graphs with events, such as a release deployment. This way you can quickly see why a particular metric has suddenly jumped up  / down.

The prometheus push gateway is an ideal tool for pushing a single event on a successful deployment, as the deployment is typically triggered from a ephemeral single-run task on a build agent. 

With the available metrics in prometheus, it is unclear what the best method of storing this data is, and how exactly to push into the push gateway in such a way to allow annotation of events on metric graphs.

Right now, we're trying to push a metric as a counter, but this is appearing every minute in our graphing, presumably due to the push gateway being scraped every minute.

It would be nice if this (fairly common) use case was covered, even briefly, in the documentation. (even if the answer was: "We don't have great support for this yet, but you can use xyz in the meantime")

**Comment by brian-brazil** [comment]
That's really an event logging use case, which isn't what Prometheus is best at. This is likely better approached from the Grafana end.

**Comment by mikeparker** [comment]
Are you saying that the data to annotate metric graphs is already supported in prometheus and grafana simply needs features adding to enable the parsing of this data?

Or do you mean we'd need to set up a 2nd separate data store (in another framework) for the metadata around the prometheus metrics?

**Comment by brian-brazil** [comment]
The latter. Prometheus has no notion of graphs or annotations of them.
