### ISSUE TITLE
Mark in the web UI if metrics are inconsistent, and consider better ways to represent it in /metrics

### ISSUE THREAD

**Issue by tcolgate** [prometheus/pushgateway#94]
The javascript prometheus client library incorrectly has the process_cpu_seconds_total registered as a gauge (due to wanting to set it to a specific value, and the counter type not supporting that).

Pushing this metric to the push gateway causes the push gateway to crash. Pushgateway's /metrics returns

`expected counter in metric process_cpu_seconds_total label:<name:"instance" value:"tristans:8181" > label:<name:"job" value:"tristan-test" > gauge:<value:0.128 >`

This is also the case with metrics other than those used by the pushgateway itself, e.g., getting two jobs to post different values for a test metr, one posting gauge, and the other posting counter causes pushgateway's /metrics to return:

`expected counter in metric metric_test label:<name:"instance" value:"tristans:8182" > label:<name:"job" value:"tristan-test" > gauge:<value:2 >`

This should probably either be handled, or rejected more gracefully when the erroneous metric is posted.

**Comment by tcolgate** [comment]
just to clairfy, there's no process panic, /metrics gives an error (we health check on /metrics on the push gateways, so our container manager kills it off)

**Comment by beorn7** [comment]
The problem with checking on posting is that the inconsistency only manifests itself upon assembling the complete /metrics scrape (smelling like O(n²) ). Thus, we needed to do so upon each push to the Pushgateway.

The current architecture tries to accept pushes really fast and processes them later, so it would be hard to return errors to the pusher. Also, it's hard to find out the "true culprit" — and only one of the two pushers inconsistent with each other will be notified.

Thus, the current behavior was introduced deliberately. But I'm happy to hear ideas how to do it better.

**Comment by tcolgate** [comment]
Could the type be ignored for subsequent pushes after the first? (clearly this means the scrape will advertise a different type then what was pushed). I guess this is mostly frustrating becase, at present, the types have no practical value.
  Could the web interface warn about the collision?

**Comment by tcolgate** [comment]
yes, I can appreciate there's not really a good solution. I guess that
"ideally" the entire name:type would be the "primary key", and you could
happily serve both. But I think that breaks a great many assumptions
elsewhere.

I've got fixes locally for the prom-client side of this, so it's much less
of a concern. This does seem like a relatively easy "accidental denial of
service", waiting to happen. But then people aren't hitting it regularly,
so it may well be a non-issue.

**Comment by beorn7** [comment]
Essentially, you want to be able to alert on inconsistent metrics being in the pushgateway.
That's semantically in a similar class with config errors.
I'll change the title of the issue accordingly.

**Comment by beorn7** [comment]
I guess you could just alert on the pushgateway being unscrapeable. You should do that anyway.

**Comment by beorn7** [comment]
#290 will effectively prevent that inconsistent metrics are pushed in the first place. It will also mark groups with rejected pushes in the UI. Thus, I'm closing this.
