### ISSUE TITLE
If parameters include '/' ,It will response code 400

### ISSUE THREAD

**Issue by Nodeman123** [prometheus/pushgateway#97]
If tags parameters include '/'  ,It will response code 400.The '/' is deal with URLEncoder. How to do?

**Comment by beorn7** [comment]
That's currently not possible.

We need to either explicitly forbid it or we need to agree on an escaping scheme.

Which then has to be coordinated across client libraries.

@brian-brazil this might interest you...

**Comment by brian-brazil** [comment]
Can you provide an example of exactly what you mean?

**Comment by beorn7** [comment]
You want to push into a grouping `job="some_job", bla="foo/bar"`. The naive URL to push to would be:
`http://localhost:9091/metrics/job/some_job/bla/foo/bar`

The PGW answers with 400 "odd number of components in label string "/bla/foo/bar", obviously.

Next try:
`http://localhost:9091/metrics/job/some_job/bla/foo%2Fbar`

The PGW answers with the same error message, and I guess that's correct as a `%2F` counts as equivalent to `/` in the path. (Doesn't it?)

**Comment by brian-brazil** [comment]
We're probably looking for an escaping scheme, and should also ensure the charset is clear.

**Comment by beorn7** [comment]
I'll try to find out how RESTful APIs handle this problem usually. (So far, I found pretty inconsistent approaches.)
If somebody has experience in the area, I'm all ears.

**Comment by curlup** [comment]
I think URI rfc3986 says that path consists of segments, which consists of pchars.
Where `pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"`
We might conclude that `%2F` should not be considered as path segment delimiter, and so `http://localhost:9091/metrics/job/some_job/bla/foo%2Fbar` should be legit. 


Also how about using uri path parameters (end of section 3.3 here https://tools.ietf.org/html/rfc3986#section-3.3)? Like `http://pushgateway.example.org:9091/metrics/job=some_job/instance=some_instance` example from docs. Or should we discuss that somewhere else?

**Comment by beorn7** [comment]
URI path parameters wouldn't follow the RESTful style.

The problem with the `%2F` escaping is that it might be legit but the Go tooling around URI parsing doesn't care. At the time the router sees the path, it's already unescaped. So we either need to circumvent the Go libraries, or we have to find another solution.

**Comment by brian-brazil** [comment]
How about switching to URL parameters?

**Comment by xianmingyuan** [comment]
Maybe this code will help you. 
```javascript
String name = "test_name";
PushGateway pushGateway = new PushGateway("127.0.0.1:9091");
CollectorRegistry registry = new CollectorRegistry();
Gauge gauge = Gauge.build()
                .name(name).help("no_help")
                .labelNames("service", "instance", "uri", "method").register(registry);
gauge.labels("test-service", "test-instance", "/test/info", "GET").set(100.00);
gauge.labels("test-service", "test-instance", "/", "POST").set(90);
gauge.labels("test-service", "test-instance", "/test", "PUT").set(56);
pushGateway.push(registry, "test-job");
registry.clear();
```

**Comment by apghero** [comment]
The problem here, _I think_ is that `httprouter.Router.ServeHTTP` uses `req.URL.Path`, instead of (likely the right choice)`req.URL.RawPath`. `RawPath` would leave the escapes as is, where as `Path` ends up unencoded. I cringe at the thought of trying to get that change in httprouter, as there's a good chance lots of people are relying on the current behavior...

**Comment by csesanram** [comment]
I have used below the code and getting following error:
java.io.IOException: Response code from http://127.0.0.1:9090/metrics/job/test-job was 404, response body: 404 page not found

Please help me this cases

String name = "test_name";
PushGateway pushGateway = new PushGateway("127.0.0.1:9090");
CollectorRegistry registry = new CollectorRegistry();
Gauge gauge = Gauge.build()
                .name(name).help("no_help")
                .labelNames("service", "instance", "uri", "method").register(registry);
gauge.labels("test-service", "test-instance", "/test/info", "GET").set(100.00);
gauge.labels("test-service", "test-instance", "/", "POST").set(90);
gauge.labels("test-service", "test-instance", "/test", "PUT").set(56);
pushGateway.push(registry, "test-job");
registry.clear();

**Comment by beorn7** [comment]
@csesanram Are you sure you are talking to the Pushgateway? It runs on port 9091 usually. (9090 is the Prometheus server itself.)

In any case, your question has nothing to do with this issue (which is about using `/` within a label value). 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
